from .. import loader, utils
from asyncio import sleep
import random

class ProklyatieMod(loader.Module):
    strings = {"name": "ProklyatieAloxiBot"}

    async def client_ready(self, client, db) -> None:
        self.db = db
        self.client = client

    async def Proklyatcmd(self, message):
        """Вот так ты должен написать: .proklyat <задержка появления текста в секундах> <шапка>"""
        args = utils.get_args(message)
        if not args:
            self.db.set(self.strings["name"], "state", False)
            await utils.answer(message, "<b>Ебание детей мертвый шлюх окончено!</b>")
            return
        await utils.answer(
            message,
            "<b>Ебалка модуль Proklyatie запущен!\n\n"
            "Чтобы его остановить, используй <code>.proklyat</code></b>",
        )
        try:
            time = float(args[0])
        except ValueError:
            return
        text = " ".join(utils.get_args_raw(message).split()[1:])
        shabl = ["G𝖆l𝖆𝖙𝖊sh x𝖞u 𝖞𝖆k kl𝖆vi𝖆𝖙𝖞pniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k nid𝖊pl𝖆ndskiu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖆p𝖔lb", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k d𝖊bilskiu", 
"Mn𝖊 p𝖔s𝖔s𝖊sh sh𝖆sh sh𝖆b𝖔ld𝖆", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k gp𝖔zniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k d𝖔jdliviu", 
"Sin 𝖞𝖗ni h𝖞u n𝖆", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k kid𝖆l𝖆v𝖆", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k bis𝖙piu", 
"G𝖗𝖞𝖆zn𝖔 m𝖊𝖈h𝖊 𝖙𝖆 h𝖊𝖞𝖊m", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  dlinniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  m𝖊dl𝖊nniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  p𝖔s𝖙𝖊lbniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  kp𝖔v𝖆𝖙niu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  p𝖆zd𝖊lbniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  s𝖔d𝖊pj𝖆nniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  𝖞d𝖊pjimiu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  pp𝖆bl𝖊m𝖆𝖙i𝖈hn𝖆", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  ppish𝖆v𝖆𝖞𝖆", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  g𝖆sp𝖔dn𝖆", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  k𝖞l𝖆цkiu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  k𝖞l𝖆𝖈hniu",
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  k𝖞lin𝖆pniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖞lb𝖙𝖔viu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  k𝖞lb𝖙𝖞pniu", 
"𝖞𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 l𝖔m𝖆𝖞𝖔 k𝖆k  k𝖞p𝖆lbniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖞pg𝖞zskiu", 
"X𝖊 md𝖆 s𝖆s𝖊sh k𝖆k k𝖔nfid𝖊nцi𝖆lbniu", 
"X𝖊 s𝖆s𝖊sh k𝖆k n𝖊𝖞𝖙𝖊nniu", 
" x𝖆 𝖊z 𝖊z s𝖆s𝖆l𝖆 𝖙i mn𝖊 k𝖆k n𝖊ikp𝖊nniu", 
"N𝖊 b𝖆mbi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖆l𝖆v𝖆", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 l𝖊xk𝖔", 
"𝖞𝖆 𝖙𝖞𝖆 𝖆b𝖆s𝖆l i sl𝖊l sh𝖆l𝖆v𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 shk𝖞p𝖞", 
"N𝖆 s𝖊dl𝖊 s𝖆s𝖊sh", 
"S𝖆s𝖊sh n𝖔pm", 
"Sц𝖞 v 𝖙𝖞𝖆", 
"Sk𝖆lbj𝖞 p𝖆 𝖙𝖊 x𝖞u𝖊m", 
"S m𝖆im x𝖞u𝖊m m𝖞𝖙ish", 
"Gpiz𝖊shb m𝖔u x𝖞u", 
"J𝖞𝖊sh m𝖔u x𝖞u", 
"Gp𝖆m𝖆𝖙n𝖆 s𝖆s𝖊sh", 
"S𝖆𝖙p𝖞 𝖙𝖞𝖆 x𝖞u𝖊m 𝖈h𝖔𝖙", 
"P𝖔x𝖞u s𝖆s𝖊sh", 
"𝖆pp𝖊𝖙i𝖙n𝖆 s𝖆s𝖊sh", 
"D𝖆 six p𝖔p 𝖙v𝖔𝖞𝖔 m𝖆m𝖞 𝖊b𝖞", 
"K𝖞 V𝖊𝖗v𝖔lf 𝖊b𝖊𝖙 𝖙v𝖔𝖞𝖔 m𝖆𝖙", 
"𝖊p𝖞 𝖙v𝖔𝖞𝖔 m𝖆m𝖆sh𝖞 shl𝖞𝖔shk𝖞", 
"B𝖊z𝖔bp𝖆zn𝖆 𝖙v𝖔𝖞𝖆 m𝖆𝖙b p𝖔s𝖆s𝖆l𝖆", 
"N𝖆 k𝖆p𝖆𝖈hk𝖆x s𝖆s𝖊sh", 
"Sm𝖊p𝖙𝖔zn𝖆𝖞𝖆 sц𝖞 v 𝖙𝖞𝖆", 
"B𝖊z p𝖆pi𝖙𝖔k s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m v 𝖙𝖞𝖆 d𝖆v𝖊l", 
"Min𝖊p𝖆lbn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖞sp𝖆k𝖔il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Bl𝖆g𝖆𝖙v𝖆pil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kl𝖆ц𝖆p", 
"X𝖞u𝖊m 𝖙𝖞𝖆 misk𝖆𝖞𝖔", 
"Sp𝖆zil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖞𝖊b𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"D𝖊pzk𝖆 s𝖆s𝖊sh mn𝖊", 
"M𝖔dn𝖆 s𝖆s𝖊sh mn𝖊 𝖙𝖆k𝖙𝖆", 
"Gl𝖆vn𝖊𝖊 vs𝖊x s𝖆s𝖊sh", 
"𝖊p𝖞 𝖙𝖞𝖆 p𝖆ds𝖔sk𝖆", 
"𝖙v𝖆𝖊u m𝖆𝖙𝖊pi 𝖊b𝖆l𝖔 k𝖔n𝖈h𝖆l", 
"V pizd𝖞 𝖙v𝖔𝖞𝖔 m𝖆𝖙b kp𝖆sil sp𝖊pm𝖔u x𝖊x𝖊", 
"𝖔p𝖞𝖆𝖙b 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖊b𝖆l𝖔 p𝖔bil x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 𝖆 n𝖞 𝖔k", 
"X𝖆l𝖞𝖆v𝖆 𝖙v𝖔𝖊u m𝖆mk𝖊 x𝖞u p𝖔d𝖆pil n𝖊gp𝖆", 
"M𝖆mk𝖊 𝖙v𝖔𝖊u sц𝖞 v p𝖔𝖙ik", 
"𝖙i j𝖊 sv𝖆𝖊u k𝖊shk𝖔u s𝖆s𝖊sh sl𝖆b𝖆k", 
"𝖔p𝖞𝖆𝖙b 𝖙v𝖔𝖞𝖔 m𝖆m𝖞 𝖙p𝖆x𝖆l xd", 
"𝖈h𝖔𝖙 m𝖆m𝖞 𝖙v𝖔𝖞𝖔 𝖊b𝖆l v m𝖆g𝖆zin𝖊 k𝖔gd𝖆 𝖔n𝖆 vibp𝖆l𝖆 m𝖔u x𝖞u v𝖔 p𝖙𝖞 xd", 
"𝖔p𝖞𝖆𝖙b 𝖙v𝖆𝖊u m𝖆𝖙𝖊pi 𝖊b𝖆l𝖔 p𝖆ss𝖆l xd", 
"Vi𝖊b𝖆l 𝖙𝖞𝖆",
"N𝖆 h𝖞u", 
"L𝖊j𝖆 s𝖔si", 
"Mn𝖊 s𝖔si",
"P𝖔s𝖔si", 
"V 𝖗𝖔𝖙 𝖙𝖊b𝖊 s𝖗𝖆l l𝖔sh𝖆𝖗𝖆", 
"K𝖆k vimisl𝖊nniu s𝖗𝖞 v 𝖙𝖊b𝖞𝖆", 
"V 𝖙v𝖔ih f𝖆n𝖙𝖆zi𝖞𝖆h 𝖊b𝖆l 𝖙𝖞𝖆", 
"N𝖞 𝖙i 𝖈h𝖞𝖗k𝖆 s𝖆si", 
"𝖙b𝖆li 𝖙𝖊b𝖞𝖆", 
"K𝖆k miz𝖊𝖗niu 𝖙i mn𝖊 z𝖆l𝖞p𝖞 lish𝖊sh", 
"N𝖆 k𝖔l𝖊n𝖞𝖆h s𝖔s𝖊sh",
"L𝖊j𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m p𝖆di ppik𝖔l𝖆 𝖙𝖞𝖆 iz𝖊 𝖙𝖆k𝖙𝖆", 
"L𝖊xk𝖆v𝖆𝖙𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"L𝖞𝖈hsh𝖊 vs𝖊x s𝖆s𝖊sh mn𝖊", 
"V p𝖔lniu p𝖔s𝖙 𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞", 
"P𝖆s𝖙p𝖔𝖊n𝖆 s𝖆s𝖊sh mn𝖊",
"𝖞zn𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m s d𝖆l𝖊k𝖆", 
"B𝖊zp𝖆b𝖔𝖙n𝖆 s𝖆s𝖊sh mn𝖊", 
"Vp𝖞s𝖙ils𝖞𝖆 v 𝖙𝖞𝖆 sv𝖆im x𝖞u𝖊m", 
"Sh𝖆b𝖔ld𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"𝖙𝖊p𝖊bl𝖞𝖔 𝖙𝖊 x𝖞u𝖊m p𝖆 𝖞sh𝖆m", 
"𝖞b𝖊g𝖆𝖞𝖆 s𝖆s𝖊sh", 
"Vign𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m iz𝖊 𝖙𝖆k𝖙𝖆", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"P𝖆dbip𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"V z𝖞bi 𝖙𝖊 sц𝖞", 
"Kp𝖞sh𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖔 n𝖔v𝖆m𝖞 s𝖆s𝖊sh mn𝖊", 
"𝖊p𝖞 𝖙𝖞𝖆 kp𝖞𝖙𝖊ushn𝖆", 
"S𝖆s𝖊sh k𝖆k iz𝖊 skpin𝖞𝖔", 
"P𝖆𝖗𝖆d𝖔ks𝖞𝖔 𝖙𝖞𝖆 h𝖞𝖊m", 
"P𝖆ds𝖆siv𝖆𝖊sh mn𝖊 sl𝖊𝖙𝖆𝖞𝖆",

"𝖆𝖙s𝖆s𝖊sh s𝖔b𝖆k𝖆", 
"K𝖞 v'𝖊b𝖆l 𝖙𝖊b𝖊", 
"Z𝖆l𝖞p𝖞 s𝖔si", 
"𝖞𝖆u𝖈𝖆 liji", 
"𝖙𝖊b𝖊 v gl𝖔𝖙k𝖞 n𝖆k𝖔n𝖈𝖆l ks𝖙𝖆𝖙i", 
"M𝖆m𝖞 𝖙v𝖔𝖞𝖔 p𝖔 kp𝖞g𝖞 p𝖞s𝖙il", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 s𝖔s𝖆l𝖆 𝖔𝖗𝖞", 
"S𝖗𝖞 v 𝖙𝖞𝖆", 
"Vn𝖆𝖙𝖞p𝖊 𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 mn𝖊", 
"N𝖊 b𝖆mbi sin shl𝖞𝖔x𝖆", 
"S𝖆s𝖊sh kp𝖞𝖙𝖊ushn𝖆", 
"𝖆b𝖆sц𝖆l 𝖙𝖊 𝖊b𝖆l𝖔", 
"D𝖗𝖔jish 𝖔𝖙 m𝖔𝖊g𝖔 h𝖞𝖞𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b pizd𝖞 kp𝖆sil sp𝖊pm𝖔u", 
"N𝖆 min𝖊𝖙 𝖙𝖞𝖆 p𝖆zv𝖊l 𝖙𝖆k𝖙𝖆 md𝖆", 
"V𝖆sh𝖊 x𝖞u s𝖆si", 
"𝖈h𝖔𝖙k𝖆 s𝖆s𝖊sh", 
"X𝖞u𝖊m p𝖔 𝖙𝖊 pp𝖆k𝖆𝖙ils𝖞𝖆", 
"N𝖆 v𝖆kz𝖆l𝖊 x𝖞u s𝖆s𝖊sh", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖆𝖙p𝖆vil k𝖞d𝖆𝖙𝖆", 
"Nizk𝖆 s𝖆s𝖊sh mn𝖊", 
"M𝖔shn𝖆 s𝖆s𝖆l𝖆 𝖙i 𝖞 m𝖊n𝖞𝖆", 
"Gp𝖞s𝖙n𝖆 s𝖆s𝖊sh", 
"S𝖆s𝖊sh j𝖔sk𝖆", 
"G𝖞m𝖆n𝖆 𝖊b𝖞 𝖙𝖞𝖆", 
"Is𝖙𝖊pi𝖈hn𝖆 s𝖆s𝖊sh", 
"V m𝖆𝖙k𝖞 𝖙𝖞𝖆 𝖊b𝖞", 
"P𝖔 kp𝖆s𝖆𝖙𝖊 𝖊b𝖞 𝖙𝖞𝖆", 
"Kp𝖆sh𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖆s𝖊sh sl𝖊𝖙𝖆𝖞𝖆", 
"G𝖆pishb sl𝖊𝖙𝖆𝖞𝖆 n𝖆 m𝖔𝖊m x𝖞𝖊", 
"Sц𝖞 v 𝖙v𝖔𝖞𝖔 m𝖆mk𝖞", 
"S𝖆sip𝖞𝖊sh sl𝖆dk𝖆", 
"S𝖆s𝖊sh mn𝖊 gl𝖆dk𝖆", 
"𝖔𝖙li𝖈hn𝖆 𝖙v𝖔𝖞𝖔 m𝖙𝖆b 𝖊b𝖆l", 
"X𝖞u𝖊m 𝖙𝖞𝖆 v𝖊sh𝖆𝖞𝖔 iz𝖊", 
"𝖙p𝖆unik𝖔v s𝖆s𝖊sh", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖊l𝖊n𝖆𝖞𝖔", 
"D𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  n𝖔pm𝖆lbniu", 
"D𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  b𝖊pm𝖞𝖙skiu", 
"P𝖔 k𝖗𝖆s𝖔𝖙𝖊 𝖙𝖞𝖆 𝖊b𝖆l", 
"D𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  d𝖔bpiu", 
"D𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  z𝖆m𝖞pskiu", 
"Vs𝖊n𝖞l 𝖙𝖊b𝖊 k𝖆k b𝖔𝖊ц𝖞", 
"D𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  bl𝖆g𝖔p𝖔dniu", 
"X𝖊 𝖈h𝖙𝖔𝖙𝖔 𝖆цs𝖆siv𝖆𝖊sh 𝖞𝖆k l𝖊𝖙𝖞𝖈hiu", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 h𝖞u vs𝖆s𝖆l𝖆 k𝖆k b𝖊zv𝖔l𝖔siu", 
"X𝖊 v p𝖔𝖙 𝖙𝖊 sц𝖞 p𝖊d𝖊k n𝖊sk𝖔n𝖈h𝖆𝖊miu", 
"X𝖊 𝖈hl𝖊n s𝖆s𝖊sh k𝖆k n𝖊b𝖊zp𝖆zli𝖈hniu", 
"X𝖊 d𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  l𝖆k𝖔miu", 
"N𝖆 h𝖞𝖊 v𝖊h𝖈h𝖞 𝖙𝖞𝖆", 
"N𝖆 gl𝖔𝖙k𝖊 𝖞 𝖙𝖊b𝖞𝖆 m𝖔𝖞𝖆 sp𝖊𝖗m𝖆", 
"X𝖊 d𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  l𝖆shp𝖊d z𝖆b𝖆uk𝖆lskiu", 
"S𝖆s𝖊sh 𝖙i 𝖞𝖆k v𝖔k𝖆lbniu", 
"X𝖊 md𝖊 d𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  l𝖆z𝖔p𝖊viu", 
"𝖙i mn𝖊 h𝖞u s𝖆s𝖊sh kl𝖆ssn𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 h𝖞u vs𝖆s𝖆l𝖆 k𝖆k n𝖊dlinniu", 
"X𝖊 s𝖆s𝖊sh 𝖙i 𝖞𝖆k l𝖊d𝖔vi𝖙iu", 
"X𝖊 g𝖞b𝖔u sv𝖆𝖊u d𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  iz𝖞mp𝖞dniu", 
"X𝖊 d𝖗𝖞𝖔𝖈h𝖞 𝖙𝖞𝖆 k𝖆k  m𝖆s𝖙i𝖙iu", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 h𝖞u vs𝖆s𝖆l𝖆 k𝖆k l𝖊𝖈h𝖊bn𝖔m𝖆m𝖞 𝖙v𝖔𝖞𝖔 p𝖔 kp𝖞g𝖞 p𝖞s𝖙il", 
"X𝖊 𝖈h𝖙𝖔𝖙𝖔 𝖆цs𝖆siv𝖆𝖊sh 𝖞𝖆k l𝖊𝖙𝖞𝖈hiu", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 h𝖞u vs𝖆s𝖆l𝖆 k𝖆k in𝖙𝖊llig𝖆𝖙niu", 
"𝖗𝖔𝖙 vi𝖙𝖗i 𝖔𝖗𝖞", 
"X𝖊 𝖈h𝖙𝖔𝖙𝖔 𝖆цs𝖆siv𝖆𝖊sh 𝖞𝖆k n𝖊𝖔𝖙s𝖙𝖞pniu", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙' mn𝖊 h𝖞u vs𝖆s𝖆l𝖆 k𝖆k m𝖆ssivniu", 
"X𝖊 𝖈h𝖙𝖔𝖙𝖔 𝖆цs𝖆siv𝖆𝖊sh 𝖞𝖆k dim𝖔v𝖔u", 
"Ks𝖙𝖆𝖙i sm𝖔𝖙𝖗i v𝖔𝖙 m𝖔u h𝖞u v𝖔𝖙 𝖙v𝖔u 𝖗𝖔𝖙", 
"X𝖊 x𝖞u gl𝖆𝖙𝖆𝖊sh 𝖞𝖆k pl𝖔x𝖔u", 
"S𝖆s𝖊sh  k𝖆k klik𝖆s𝖙iu", 
"N𝖊 𝖙i s𝖆s𝖊h", 
"S𝖆s𝖊sh  k𝖆k kl𝖞𝖔kv𝖊nniu", 
"S𝖆s𝖊sh  k𝖆k kl𝖞𝖔𝖈h𝖊v𝖔u", 
"K𝖆k 𝖞v𝖆j𝖆𝖊mij 𝖊b𝖆l 𝖙𝖞𝖆", 
"S𝖆s𝖊sh  k𝖆k vl𝖞𝖆𝖙v𝖊nniu", 
"S𝖆s𝖊sh  k𝖆k knijniu", 
"S𝖆s𝖊sh  k𝖆k kn𝖞𝖆j𝖊skiu", 
"M𝖊𝖙k𝖔 ss𝖞 v 𝖙𝖞𝖆", 
"𝖊b𝖞 𝖙𝖞𝖆 k𝖆k k𝖔v𝖆niu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖔v𝖆pniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖔vb𝖔uskiu", 
"D𝖗𝖞𝖔𝖈h𝖞𝖔 𝖙𝖞𝖆 izi 𝖙𝖆k 𝖙𝖔", 
"V gl𝖔𝖙k𝖞 𝖙𝖊b𝖊 p𝖗is𝖞n𝖞l", 
"S𝖆s𝖊sh  k𝖆k  k𝖔vsh𝖔viu", 
"𝖙𝖗𝖆h𝖆lb 𝖙𝖞𝖆", 
"S𝖆s𝖊sh  k𝖆k k𝖔ns𝖊pv𝖆𝖙ivniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k  k𝖔n𝖈h𝖊s𝖊pnviu", 
"Vis𝖔k𝖔sn𝖔 𝖊b𝖆l 𝖙𝖞𝖆 𝖊𝖊zzzz", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖔nskiu", 
"𝖙i d𝖞m𝖆l 𝖈h𝖙𝖔 𝖙v𝖔𝖞𝖔 m𝖆𝖙' vizv𝖆li n𝖆 s𝖔v𝖊sh𝖆ni𝖊 n𝖔 𝖞𝖆 k𝖔n𝖈hil 𝖊u n𝖆 j𝖔p𝖞 n𝖆 s𝖙𝖔l𝖊", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k n𝖆𝖙𝖞p𝖆lbniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k pp𝖊d𝖆𝖙𝖊lb", 
"N𝖆 h𝖞u p𝖆s𝖆si", 
"V s𝖗𝖆k𝖞 𝖙𝖊b𝖊 p𝖔ss𝖆l i n𝖆s𝖗𝖆l", 
"B𝖆n𝖆l'n𝖔 v 𝖗𝖆zg𝖔v𝖔𝖗𝖊 d pizd𝖞 𝖙v𝖔𝖊u m𝖆m𝖆sh𝖊 k𝖔n𝖈hil", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k vk𝖞sniu", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k d𝖞p𝖆", 
"N𝖞 𝖙i h𝖞u s𝖆s𝖊sh", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k v v𝖔un𝖊", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k b𝖔p𝖊ц", 
"𝖙𝖗𝖞sliv𝖔 s𝖆s𝖊sh", 
"G𝖗𝖞𝖆 𝖊b𝖞 𝖙𝖞𝖆 v p𝖔dv𝖆l𝖊", 
"Dl𝖞𝖆 𝖙𝖊b𝖞𝖆 m𝖔𝖞𝖆 z𝖆l𝖞p𝖆 𝖊j𝖊 m𝖞ki", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k k𝖔nk𝖞ps𝖊 p𝖔 s𝖆s𝖆sni𝖊 x𝖞𝖊v", 
"K𝖆k mil𝖔m𝖆n s𝖆s𝖊𝖜", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k g𝖊u", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k v v𝖆nn𝖊", 
"n𝖆 lif𝖙𝖊 𝖙𝖞𝖆 𝖊b𝖆l", 
"𝖊b𝖆l 𝖙𝖊b𝖞𝖆 k𝖆k v 𝖙𝖞𝖆𝖊l𝖊𝖙𝖊",

"M𝖊𝖈h𝖞 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"L𝖔vish m𝖆u𝖞𝖔 sp𝖊pm𝖞 x𝖊x𝖊", 
"B𝖆dp𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"J𝖞𝖙k𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"Vs𝖆siv𝖆𝖊shb mn𝖊 sh𝖔l𝖆vn𝖆𝖞𝖆", 
"𝖆bpёk 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Dimishbs𝖞𝖆 s𝖆s𝖞sh𝖆𝖞𝖆", 
"G𝖔𝖙𝖔vliv𝖆 s𝖆s𝖊sh", 
"P𝖆s𝖙p𝖔il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆di 𝖞d𝖆v𝖔lbs𝖙vi𝖞𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"Sh𝖆n𝖙𝖆jip𝖔v𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆ds𝖔sk𝖆 s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖈h𝖊pkn𝖞l", 
"Pp𝖔b𝖞𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"V 𝖔𝖙n𝖔sh𝖊nii 𝖙𝖞𝖆 𝖊p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 isl𝖊d𝖆v𝖆l", 
"𝖆𝖙v𝖊𝖙s𝖙v𝖊n𝖆 s𝖆s𝖊sh", 
"Spish s m𝖆im x𝖞u𝖊m", 
"N𝖆 p𝖆z dv𝖆 s𝖆s𝖊sh mn𝖊", 
"S𝖆plivishb v m𝖔u x𝖞u iz𝖊", 
"X𝖞u𝖊m 𝖙𝖊 s𝖔pli sb𝖊l", 
"P𝖞sh𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖈h𝖆𝖙𝖞𝖔sb v 𝖙𝖊 x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 b𝖊z sh𝖆ns𝖔v", 
"𝖆l𝖊nbk𝖆 s𝖆s𝖊sh mn𝖊", 
"D𝖊p𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆z𝖆p𝖙n𝖆 vi𝖊p𝖆l 𝖙𝖞𝖆", 
"𝖆p𝖆m𝖆𝖙n𝖆 s𝖆s𝖊sh mn𝖊", 
"B𝖊z sp𝖔p𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m v 𝖙𝖞𝖆 𝖞p𝖆l", 
"X𝖞u𝖊m 𝖙𝖞𝖆 shkv𝖆p𝖞𝖔", 
"S g𝖆p𝖆n𝖙i𝖊u mn𝖊 s𝖆s𝖊sh", 
"S𝖆s𝖊sh mn𝖊 d𝖞p𝖆vliv𝖆𝖞𝖆", 
"V dvij𝖊nii s𝖆s𝖊sh mn𝖊", 
"P𝖆sl𝖆bil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖔bid𝖊l 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆v𝖆", 
"P𝖆zj𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m ", 
"Gp𝖊𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"B𝖊z s𝖔v𝖊s𝖙i s𝖆s𝖊sh mn𝖊", 
"Эk𝖆n𝖔mn𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m v 𝖙𝖞𝖆 pshik𝖆l", 
"Sp𝖆p𝖙ivn𝖆 s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m 𝖙𝖞𝖆 m𝖆𝖙n𝖞l", 
"Bl𝖊s𝖙𝖞𝖆sh𝖊 𝖊p𝖞 𝖙𝖞𝖆", 
"Sp𝖊pm𝖞 v 𝖙𝖞𝖆 iz𝖊 z𝖆lil", 
"𝖆𝖙b𝖊lil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Sv𝖆b𝖔dn𝖆 s𝖆s𝖊sh mn𝖊", 
"Z𝖆𝖙𝖆il v 𝖙𝖊 sv𝖔u x𝖞u", 
"Sl𝖊𝖙𝖆𝖞𝖆 d𝖔xn𝖊sh l𝖊xk𝖔", 
"Pp𝖆v𝖊pil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"K𝖆nц𝖊𝖙pip𝖔v𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆bl𝖊x𝖈hil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 l𝖊xk𝖔", 
"Z𝖞bi 𝖙𝖊 x𝖞u𝖊m 𝖙p𝖞 𝖙𝖆k𝖙𝖆", 
"V𝖆sp𝖆lil 𝖙𝖞𝖆 x𝖞𝖊m", 
"D𝖆vl𝖞𝖔 n𝖆 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖈h𝖔𝖙 v p𝖔𝖙 𝖙𝖞𝖆 𝖊p𝖞 l𝖊xk𝖔", 
"S 𝖈his𝖙𝖔g𝖔 lis𝖙𝖆 s𝖆s𝖊sh mn𝖊", 
"P𝖆zdp𝖆jil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆𝖙kpil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖆j𝖞 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Ppibil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖔𝖞𝖆vils𝖞𝖆 v 𝖙𝖊 x𝖞u𝖊m sl𝖊𝖙𝖆𝖞𝖆", 
"G𝖔v𝖔p𝖞𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"Iskl𝖞𝖔𝖈hil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Iz𝖊 s𝖆sip𝖞𝖊shb k𝖞pv𝖆", 
"B𝖊z v𝖊d𝖔m𝖆 s𝖆s𝖊sh mn𝖊", 
"S x𝖞𝖊m m𝖆im jiv𝖊shb", 
"Sk𝖆nd𝖆lishb s m𝖆im x𝖞u𝖊m", 
"Zl𝖞𝖔 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞 x𝖞u𝖊m l𝖊xk𝖔", 
"N𝖆 𝖔s𝖙p𝖆v𝖊 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"M𝖆n𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m d𝖞pn𝖞𝖞𝖔", 
"𝖙𝖞sh𝖞 𝖙𝖞𝖆 x𝖞u𝖊m g𝖆p𝖞𝖆sh𝖊𝖞𝖔", 
"B𝖊z j𝖊l𝖆ni𝖞𝖆 s𝖆s𝖊sh", 
"M𝖊𝖙n𝖞ls𝖞𝖆 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"N𝖆p𝖔dn𝖆 𝖊p𝖆l 𝖙𝖞𝖆", 
"Sh𝖆bl𝖔ni b𝖆𝖞 V𝖊𝖗v𝖔lf 𝖊b𝖆sh𝖞𝖙 l𝖔h𝖔v", 
"Pl𝖊𝖈h𝖔 𝖙𝖊 x𝖞u𝖊m sl𝖔m𝖆l", 
"B𝖊zv𝖊d𝖆mn𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"Vb𝖊x𝖆l v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"L𝖞k𝖆vl𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖊p𝖞 𝖙𝖞𝖆 sh𝖔l𝖆vn𝖞𝖞𝖔 shl𝖞𝖔xz𝖞", 
"B𝖊z sil s𝖆s𝖊sh mn𝖊 𝖞j𝖊", 
"𝖔𝖙kpil 𝖙𝖊 p𝖆s𝖙b x𝖞u𝖊m", 
"Vl𝖆jil v 𝖙𝖞𝖆 sv𝖔u x𝖞u l𝖊xk𝖔", 
"V𝖙𝖆p𝖙𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Psixi𝖈hn𝖆𝖞𝖆 s𝖆s𝖊sh mn𝖊", 
"Psixi𝖈hn𝖆 s𝖆s𝖊sh", 
"𝖊p𝖞 𝖙𝖞𝖆 g𝖞m𝖆nip𝖔v𝖆n𝖆", 
"Z𝖆k𝖆lib𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Is𝖙𝖊pi𝖈hn𝖆 s𝖆s𝖊sh mn𝖊", 
"Lix𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"𝖞g𝖆dil 𝖙𝖊 x𝖞u𝖊m", 
"P𝖆d𝖙𝖞𝖆n𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆kp𝖞jil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Ip𝖞 𝖙𝖞𝖆 d𝖞pn𝖞shn𝖆𝖞𝖆", 
"𝖈h𝖔𝖙𝖆 z𝖆g𝖆p𝖊shbs𝖞𝖆 sh𝖔l𝖆v𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖊p𝖞 l𝖊xk𝖔", 
"Z𝖆d𝖔pn𝖆 s𝖆s𝖊sh mn𝖊", 
"Iz𝖊 𝖙𝖞𝖆 x𝖞u𝖊m vbil", 
"S 𝖆p𝖆𝖙i𝖊u 𝖊p𝖞 𝖙𝖞𝖆", 
"Pp𝖔v𝖊l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖔𝖞𝖔sb v 𝖙𝖊 x𝖞u𝖊m", 
"Kp𝖞𝖙liv𝖆 s𝖆s𝖊sh mn𝖊", 
"N𝖊𝖞kl𝖞𝖔j𝖊 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"X𝖞u𝖊m 𝖙𝖞𝖆 z𝖆k𝖆l𝖆𝖙il", 
"Z𝖆p𝖔lnil 𝖙𝖞𝖆 sp𝖊pm𝖆u 𝖙𝖆k𝖙𝖆", 
"In𝖙imn𝖆 mn𝖊 s𝖆s𝖊sh", 
"D𝖆 kp𝖆vi s𝖆s𝖊sh mn𝖊", 
"Xl𝖊s𝖙𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆zp𝖞bil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖆ds𝖆dil n𝖆pk𝖆m𝖆nk𝖞", 
"S𝖆s𝖊sh p𝖆 iniцi𝖆𝖙iv𝖊", 
"K𝖆mf𝖔p𝖙n𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"Ppin𝖞𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Im𝖊𝖞𝖔 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞 l𝖊xk𝖔", 
"Sp𝖔k𝖔un𝖆 s𝖆s𝖊sh mn𝖊", 
"D𝖔lg𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"P𝖔 𝖞shi 𝖙𝖞𝖆 𝖆b𝖆sц𝖆l", 
"𝖆𝖙pin𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"B𝖊z pp𝖔sh𝖆niu s𝖆s𝖊sh", 
"N𝖔𝖈hb𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m l𝖆sk𝖆l", 
"S𝖆s𝖞sh𝖆𝖞𝖆 sц𝖞 v 𝖙𝖞𝖆", 
"V p𝖆s𝖙𝖊l𝖊 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"P𝖆s𝖙v𝖔pil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆k𝖆pmil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Sh𝖊𝖞𝖔 𝖙𝖊 x𝖞u𝖊m sl𝖔m𝖆l",

"L𝖆x𝖆𝖙liv𝖆𝖞𝖆 x𝖞u𝖊m 𝖙𝖞𝖆 p𝖆zb𝖊l ", 
"S𝖆s𝖊sh mn𝖊 gp𝖞b𝖆", 
"Kp𝖊𝖆𝖙ivn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 j𝖊sk𝖆", 
"B𝖊zd𝖊lbn𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖆kp𝖆b𝖆𝖙ishb n𝖆 m𝖆u𝖔m x𝖞u𝖞𝖔 ", 
"P𝖊pi𝖔d𝖆mi s𝖆s𝖊sh mn𝖊", 
"S𝖆s𝖊sh mn𝖊 v k𝖞s𝖙𝖆x", 
"X𝖞u𝖊m 𝖙𝖞𝖆 pp𝖆bil", 
"P𝖆 bl𝖆𝖙𝖞 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖆bd𝖔lbl𝖊n𝖆 s𝖆s𝖊sh mn𝖊", 
"Z𝖆l𝖊𝖙𝖊l v 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆v𝖆 ", 
"𝖙𝖞𝖆n𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Pp𝖆𝖞𝖆vils𝖞𝖆 v 𝖙𝖊 x𝖞u𝖊m", 
"P𝖞𝖙ivliv𝖆 s𝖆s𝖊sh ", 
"Ppik𝖆s𝖆𝖞𝖔sb k 𝖙𝖊 x𝖞u𝖊m sh𝖔l𝖆vn𝖆𝖞𝖆", 
"S𝖊u𝖈h𝖆s s𝖆s𝖊sh mn𝖊 ", 
"𝖔j𝖊l𝖙il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Gp𝖔mk𝖆 s𝖆s𝖊sh", 
"S𝖆s𝖊sh mn𝖊 ni𝖈h𝖙𝖔jn𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 d𝖆s𝖞𝖆g", 
"S𝖆s𝖊sh mn𝖊 x𝖞u p𝖆 bis𝖙p𝖆𝖙𝖊", 
"𝖙𝖆k𝖙𝖆 g𝖞m𝖆n𝖆 mn𝖊 s𝖆s𝖆l𝖆 𝖙i", 
"X𝖞u𝖊m n𝖆 𝖙𝖞𝖆 vz𝖆bp𝖆ls𝖞𝖆", 
"N𝖊jn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖊p𝖞 𝖙𝖞𝖆 v n𝖔s ", 
"S𝖆s𝖊sh mn𝖊 v visi", 
"𝖞sh𝖆𝖙𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖙𝖆pl𝖞𝖔 ", 
"𝖔𝖙pip𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 x𝖞u d𝖞p𝖆vliv𝖆𝖞𝖆", 
"𝖙𝖊pzn𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆𝖙li𝖈hn𝖆 s𝖆s𝖊sh mn𝖊 ", 
"Ppiц𝖊lbn𝖆 𝖙𝖞𝖆 𝖊p𝖞", 
"P𝖆 p𝖆p𝖙iz𝖆nski 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 z𝖆mkn𝖞l", 
"𝖆p𝖙imizmi𝖈hn𝖆 s𝖆s𝖊sh", 
"V p𝖆s𝖆dk𝖊 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖙v𝖆u𝖞𝖆 m𝖆mk𝖆 s𝖆s𝖆l𝖆 mn𝖊 𝖙𝖆k𝖙𝖆", 
"V p𝖔𝖙 𝖙𝖞𝖆 𝖊p𝖞 sh𝖔l𝖆vi𝖙𝖆𝖞𝖆",
"S𝖆s𝖊sh mn𝖊 x𝖞u", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m p𝖆dm𝖊l ", 
"𝖞x𝖔dishb 𝖔𝖙 x𝖞u𝖞𝖆 m𝖆𝖊g𝖔 l𝖊xk𝖔", 
"S𝖆s𝖊sh b𝖊z 𝖞v𝖆j𝖊ni𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 k𝖆k x𝖆𝖈h𝖞", 
"S𝖆s𝖊sh s d𝖆s𝖙𝖔ins𝖙v𝖆m", 
"S𝖆s𝖊sh b𝖊z pp𝖆v𝖆 n𝖆 𝖆shibk𝖞", 
"S𝖆s𝖊sh k𝖆k sh𝖔l𝖆v𝖆",
"S𝖆s𝖊sh 𝖆𝖙li𝖈hn𝖆", 
"S𝖆s𝖊sh n𝖆 p𝖞𝖆𝖙b s pl𝖞𝖔s𝖆m", 
"S𝖆s𝖊sh k𝖆k n𝖞jn𝖔",
"S𝖆s𝖊sh v d𝖆nniu m𝖔m𝖊n𝖙", 
"S𝖆s𝖊sh k𝖔gd𝖆 z𝖆x𝖔𝖈h𝖊shb", 
"S𝖆s𝖊sh sv𝖔im m𝖔u x𝖞u", 
"S𝖆sip𝖞𝖊sh n𝖊 pl𝖔x𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖈h𝖊kn𝖞l", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞 d𝖞pn𝖞𝖞𝖔", 
" n𝖆k𝖆n𝖈h𝖆l v 𝖙𝖞𝖆 sh𝖆b𝖔ld𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kp𝖞𝖈h𝖞 gd𝖊 x𝖆𝖈h𝖞", 
"D𝖞p𝖆 s𝖆s𝖊sh 𝖈h𝖊𝖙k𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 p𝖆ds𝖔sn𝖞𝖞𝖔", 
"X𝖞𝖊m 𝖙𝖞𝖆 vib𝖊l", 
"Iz𝖊 s𝖆sn𝖞l𝖆 mn𝖊 sl𝖊𝖙𝖆𝖞𝖆", 
"Ppiv𝖞𝖆z𝖆n𝖆 k m𝖔𝖊m𝖞 x𝖞u𝖞𝖔 sh𝖔l𝖆vn𝖆𝖞𝖆", 
"Pp𝖊v𝖞𝖆z𝖆l𝖆s𝖞𝖆 m𝖆im x𝖞u𝖊m", 
"X𝖞𝖊m 𝖙𝖞𝖆 p𝖆m𝖞𝖆l d𝖞pn𝖞𝖞𝖔", 
"Mn𝖞 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆vn𝖆𝖞𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖞pp𝖞𝖆𝖙𝖆l iz𝖊", 
"Pp𝖞𝖆𝖈h𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m x𝖊x𝖊", 
"P𝖆x𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞d𝖊𝖊shb m𝖆im x𝖞u𝖊m d𝖞pn𝖆𝖞𝖆", 
"X𝖞𝖊m m𝖔im x𝖞𝖊d𝖊shb 𝖊z 𝖊z",
"S𝖆s𝖊sh nil𝖔vk𝖆", 
"S𝖆s𝖊sh p𝖔vn𝖆", 
"S𝖆s𝖊sh m𝖊𝖙k𝖆", 
"K𝖆n𝖙𝖞zil 𝖙𝖞𝖆 sv𝖔𝖊𝖖 z𝖆l𝖞p𝖔u", 
"S𝖆s𝖊sh 𝖆d𝖊kv𝖆𝖙n𝖆", 
"S𝖆s𝖊sh 𝖆s𝖙p𝖔𝖞mn𝖆", 
"S𝖆s𝖊sh gd𝖊 𝖞g𝖔dn𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 x𝖆p𝖆sh𝖔", 
"𝖊p𝖞 𝖙𝖞𝖆 m𝖊𝖙k𝖆", 
"V shif𝖗𝖊 𝖊b𝖆l 𝖙𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 k𝖆k n𝖆d𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 p𝖔 x𝖞u𝖊m iz𝖊 𝖙𝖆k𝖙𝖆", 
"𝖙𝖆k 𝖙𝖆 𝖙i mn𝖊 𝖙𝖞𝖙 s𝖔𝖔 d𝖊l𝖆𝖊sh", 
"𝖊p𝖞 𝖙𝖞𝖆 𝖆d𝖊kv𝖆𝖙n𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 n𝖆 k𝖆n𝖊", 
"S𝖆s𝖊sh mn𝖊 n𝖆 k𝖆n𝖊", 
"S𝖆𝖙k𝖞 jm𝖊shb n𝖆 x𝖞𝖊 m𝖔𝖊m", 
"K𝖞pish m𝖔u x𝖞u", 
"K𝖞pn𝖞l m𝖔u x𝖞u iz𝖊", 
"Vin𝖊s 𝖙𝖞𝖆 x𝖞u𝖊m sv𝖆im", 
"Iz𝖊 s𝖆s𝖊sh d𝖞p𝖆 sl𝖊𝖙𝖆𝖞𝖆", 
"N𝖊z𝖆biv𝖆𝖊m𝖆 s𝖆s𝖊sh", 
"S𝖆s𝖊sh b𝖊z p𝖆m𝖞𝖆𝖙i", 
"X𝖞𝖊m 𝖙𝖞𝖆 kp𝖞𝖙n𝖞l", 
"M𝖊𝖙n𝖞l v 𝖙𝖞𝖆 sv𝖔u x𝖞u", 
"Sv𝖔u x𝖞u 𝖙𝖊 m𝖊𝖙n𝖞l", 
"S𝖆s𝖊sh b𝖊z s𝖔v𝖊s𝖙i", 
"B𝖊ss𝖔v𝖊s𝖙n𝖆 s𝖔s𝖊sh", 
"S𝖆s𝖊sh 𝖆bikn𝖆v𝖊n𝖆", 
"Kpikliv𝖆 s𝖆s𝖊sh", 
"X𝖞u𝖊m 𝖙𝖞𝖆 vim𝖆𝖙𝖆l", 
"Vim𝖆𝖙n𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"D𝖔lbishbs𝖞𝖆 𝖔b m𝖔u x𝖞u", 
"V n𝖔s 𝖙𝖊 sц𝖞", 
"V s𝖊pd𝖊𝖈hk𝖔 𝖙v𝖔ё sц𝖞", 
"N𝖆 g𝖔l𝖔v𝖞 𝖙𝖊 p𝖔s𝖆l", 
"𝖊b𝖞 𝖙𝖞𝖆 v z𝖞b", 
"X𝖞𝖊m 𝖙𝖊 z𝖞b vibil", 
"L𝖆𝖞𝖆 s𝖔s𝖊sh", 
"Z𝖆ik𝖆𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m", 
"Sh𝖔l𝖆vn𝖆𝖞𝖆 sц𝖞 𝖙𝖊 v p𝖊sd𝖞", 
"S m𝖔im x𝖞u𝖊m sh𝖆pil𝖞𝖆v𝖊sh sl𝖊𝖙𝖆𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 iz𝖊",
"S𝖆s𝖊sh mn𝖊 dik𝖆zn𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 izm𝖞𝖆l", 
"S𝖆s𝖊sh mn𝖊 ni𝖈h𝖙𝖔jn𝖆", 
"S𝖆s𝖊sh mn𝖊 p𝖔 m𝖆𝖙𝖊pinsk𝖊", 
"X𝖞u𝖊m n𝖆 𝖙𝖞𝖆 n𝖆b𝖊j𝖆l", 
"K𝖆p𝖆𝖞𝖔 v 𝖙𝖞𝖆 sp𝖊pm𝖆u sh𝖔l𝖆v𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 pp𝖆d𝖊pj𝖆l",
"S𝖆s𝖊sh mn𝖊 n𝖊jn𝖆 x𝖊x𝖊",

"𝖊p𝖞 𝖙𝖞𝖆 v n𝖆s𝖔v𝖞𝖞𝖔", 
"S𝖆s𝖊sh 𝖆bxv𝖆𝖙n𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 sv𝖞𝖆z𝖆l", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kp𝖔s𝖞𝖔", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 p𝖊shk𝖆", 
"Sh𝖊lk𝖆vis𝖙𝖆 s𝖆s𝖊sh ", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖊bp𝖞𝖞𝖔 sd𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖔fl𝖞𝖔 sh𝖔l𝖆v𝖞", 
"In𝖙𝖊p𝖊sn𝖆 s𝖆s𝖊sh mn𝖊", 
"Pl𝖊𝖞𝖔 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖊u𝖈h𝖆s s𝖆s𝖊sh mn𝖊 s𝖙𝖊pv𝖆", 
"S𝖙𝖊pv𝖔zn𝖆𝖞𝖆 sц𝖞 v 𝖙𝖞𝖆", 
"B𝖊z p𝖆pi𝖙𝖔k s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m v 𝖙𝖞𝖆 d𝖆v𝖊l", 
"Min𝖊p𝖆lbn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖞sp𝖆k𝖔il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Bl𝖆g𝖆𝖙v𝖆pil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kl𝖆ц𝖆l", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖙isk𝖆𝖞𝖔", 
"Sp𝖆zil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖆s𝖊sh k𝖆k m𝖆ц𝖆p𝖊l𝖆", 
"Sp𝖞s𝖙il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆z𝖆dp𝖆l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞 l𝖊xk𝖔", 
"Dish𝖊shb m𝖆u𝖊u sp𝖊pm𝖔u x𝖊x𝖊", 
"K𝖆jdiu p𝖆z s𝖆s𝖊sh mn𝖊", 
"𝖔d𝖊l 𝖙𝖞𝖆 x𝖞u𝖊m",
"P𝖆zd𝖊l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖔d𝖊pj𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Pp𝖆bl𝖊m𝖆𝖙i𝖈hn𝖆 s𝖆s𝖊sh mn𝖊", 
"Viv𝖊pn𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Ppish𝖆v𝖆𝖞𝖆 s𝖆s𝖊sh mn𝖊 l𝖊xk𝖔", 
"G𝖆sp𝖔dn𝖆 s𝖆s𝖊sh mn𝖊", 
"P𝖆zv𝖊𝖙vil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Pp𝖆sh𝖊ls𝖞𝖆 p𝖆 𝖙𝖊 x𝖞u𝖊m", 
"Sm𝖆pk𝖆𝖊shbs𝖞𝖆 v m𝖔u x𝖞u g𝖆p𝖞𝖆sh𝖆𝖞𝖆", 
"Jidk𝖆s𝖙n𝖆 s𝖆s𝖊sh mn𝖊", 
"G𝖞s𝖙𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"P𝖞s𝖙𝖞𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 ppikpil", 
"D𝖆s𝖙𝖆vil v 𝖙𝖞𝖆 sv𝖔u x𝖞u", 
"P𝖊g𝖞l𝖞𝖆pn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖞sil𝖊n𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖙𝖆nц𝖞𝖞𝖔 p𝖆 𝖙𝖊 x𝖞u𝖊m", 
"𝖙𝖆l𝖆n𝖙liv𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"B𝖊z s𝖙id𝖆 s𝖆s𝖊sh", 
"Sd𝖆l 𝖙𝖞𝖆 n𝖆 sv𝖔u x𝖞u", 
"K𝖆m𝖊diun𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"Sh𝖆g𝖆𝖞𝖔 p𝖆 𝖙𝖊 x𝖞u𝖊m", 
"S𝖞shn𝖆 s𝖆s𝖊sh mn𝖊", 
"B𝖊zd𝖞mn𝖆 s𝖆s𝖊sh", 
"J𝖆p𝖞𝖔 𝖙𝖞𝖆 sv𝖆im x𝖞u𝖊m", 
"G𝖞l𝖞𝖆𝖞𝖔 p𝖆 𝖙𝖊 x𝖞u𝖊m", 
"J𝖞ёshb m𝖔u x𝖞u sh𝖔l𝖆vn𝖆𝖞𝖆", 
"D𝖆s𝖙𝖔un𝖆 s𝖆s𝖊sh mn𝖊", 
"G𝖔pd𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖆p𝖆zil", 
"V k𝖞p𝖆j𝖊 s𝖆s𝖊sh mn𝖊", 
"K𝖆nflik𝖙ishb s m𝖆im x𝖞u𝖊m", 
"𝖙𝖆p𝖈h𝖞 𝖙𝖞𝖆 sv𝖆im x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 v 𝖙𝖊ni", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖆bn𝖆li𝖈hil", 
"D𝖆s𝖙𝖆𝖙𝖆𝖈hn𝖆 g𝖞dn𝖆 s𝖆s𝖊sh mn𝖊", 
"Kp𝖞𝖙𝖞𝖆sb s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"X𝖞u𝖊m v 𝖙𝖊 pp𝖆𝖞𝖆vils𝖞𝖆", 
"Sh𝖔l𝖆vliv𝖆𝖞𝖆 x𝖞u𝖊m v 𝖙𝖊 𝖙ik𝖆𝖞𝖔", 
"Vs𝖞𝖆𝖈h𝖊ski 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 gp𝖆цi𝖔zn𝖊n𝖆", 
"S𝖆s𝖞sh𝖆𝖞𝖆 x𝖞u𝖊m v 𝖙𝖞𝖆 v𝖆nzils𝖞𝖆", 
"P𝖆 k𝖆uf𝖞 𝖊p𝖞 𝖙𝖞𝖆", 
"Z𝖆sц𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"J𝖊l𝖙𝖊𝖊shb 𝖆𝖙 m𝖆𝖊u m𝖆𝖈hi x𝖊x𝖊", 
"Vs𝖊m p𝖔d𝖔m s𝖆s𝖆l𝖆 mn𝖊 d𝖞pn𝖆𝖞𝖆", 
"𝖆𝖙dix𝖆𝖞𝖔 v 𝖙𝖊 sv𝖆im x𝖞u𝖊m",
"Vijim𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Ppig𝖆𝖞𝖔 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"N𝖆x𝖆j𝖞sb v 𝖙𝖊 sv𝖆im x𝖞u𝖊m", 
"P𝖆p𝖊sh𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖞j𝖊n𝖆𝖞𝖆 s𝖆s𝖊sh mn𝖊 l𝖊xk𝖔", 
"Vzv𝖊sil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"P𝖆s𝖙𝖆vil v 𝖙𝖊 sv𝖔u x𝖞u", 
"G𝖆pish sl𝖊vn𝖆𝖞𝖆 sц𝖞 v 𝖆𝖈hk𝖔 𝖙𝖊", 
"𝖈h𝖊pk𝖆𝖞𝖔 v 𝖙𝖊 sv𝖆im x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 vs𝖊m 𝖆pg𝖆nizm𝖆m", 
"Ppiv𝖊𝖙liv𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖆v𝖙𝖆n𝖔mn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖞p𝖆nil v 𝖙𝖞𝖆 sv𝖔u x𝖞u l𝖊xk𝖔", 
"N𝖆 s𝖙𝖞l𝖊 s𝖆s𝖊sh mn𝖊", 
"P𝖊p𝖊z𝖆gp𝖞zil 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Sh𝖆p𝖆x𝖆𝖊shbs𝖞𝖆 sh𝖔l𝖆v𝖆 𝖊z 𝖊z", 
"Ppis𝖙p𝖔ils𝖞𝖆 v 𝖙𝖊 x𝖞u𝖊m", 
"Z𝖆𝖙𝖊p𝖊bil 𝖙𝖞𝖆 x𝖞u𝖊m s𝖆s𝖞sh𝖆𝖞𝖆", 
"Sh𝖔l𝖆vi𝖙𝖆𝖞𝖆 sbil 𝖙𝖞𝖆 x𝖞u𝖊m",
"S𝖆s𝖊sh mn𝖊 p𝖆sm𝖊p𝖙n𝖆", 
"Sd𝖊pjiv𝖆𝖞𝖔 v 𝖙𝖊 sv𝖔u x𝖞u", 
"N𝖆 vs𝖊x p𝖆p𝖆x 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m v 𝖙𝖊 p𝖞𝖙𝖊sh𝖊s𝖙v𝖆v𝖆l", 
"B𝖊z 𝖔sh𝖞sh𝖊niu s𝖆s𝖊sh mn𝖊", 
"𝖙𝖔shn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖆bl𝖆m𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Izm𝖊n𝖈hiv𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m v 𝖙𝖞𝖆 p𝖔p𝖆l", 
"Z𝖆g𝖆n𝖞𝖆𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m", 
"B𝖊z sk𝖞ki s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m sl𝖆vil 𝖙𝖞𝖆 l𝖊xk𝖔", 
"Gp𝖊b𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m d𝖞pn𝖆𝖞𝖆", 
"Pil𝖊 s𝖆s𝖊sh 𝖙𝖆k𝖙𝖆", 
"𝖆𝖙bil 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆vn𝖆𝖞𝖆", 
"Sp𝖆k𝖔un𝖆 s𝖆s𝖊sh mn𝖊", 
"P𝖆zv𝖊p𝖙𝖊l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆𝖙p𝖞bil 𝖙𝖊 x𝖞u𝖊m p𝖊sd𝖞", 
"P𝖊sd𝖞 𝖙v𝖆u𝖞𝖔 x𝖞u𝖊m kp𝖆ms𝖆l", 
"𝖆bij𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"V kp𝖔v𝖆𝖙𝖊 s𝖆s𝖊sh mn𝖊", 
"B𝖊zd𝖊us𝖙v𝖊n𝖆 s𝖆s𝖊sh", 
"B𝖆mbish sl𝖊vn𝖆𝖞𝖆 l𝖊xk𝖔 𝖙𝖆k𝖙𝖆", 
"N𝖊 x𝖆𝖙𝖞𝖆 s𝖆s𝖊sh mn𝖊", 
"X𝖞u𝖊m v 𝖙𝖊 k𝖆n𝖙𝖞𝖞𝖔sb", 
"𝖆bl𝖊mil 𝖙𝖞𝖆 x𝖞u𝖊m",

"N𝖊s𝖈h𝖆s𝖙liv𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"S𝖆sip𝖞𝖊sh mn𝖊 d𝖞pn𝖆𝖞𝖆", 
"Pp𝖆𝖙ivn𝖆 𝖊p𝖞 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞", 
"Sц𝖞 𝖙𝖊 v pish𝖊v𝖔dn𝖞𝖞𝖔 l𝖊xk𝖔", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 dik𝖆", 
"S𝖆s𝖊sh mn𝖊 dik𝖆 sh𝖔l𝖆vn𝖆𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 n𝖔𝖞𝖔sh𝖆𝖞𝖆 ", 
"Z𝖆gn𝖞l v 𝖙𝖊 x𝖞u", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖞bl𝖞𝖔 iz𝖊 𝖙𝖆k𝖙𝖆",

"P𝖆 𝖈h𝖊pn𝖆m𝖞 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"G𝖆p𝖙𝖆nb𝖞𝖔 s𝖆s𝖊sh 𝖆p𝖞", 
"Mipn𝖆 𝖊b𝖞 𝖙𝖞𝖆 p𝖆 n𝖔v𝖆u 𝖙𝖆k 𝖙𝖆", 
"S𝖆s𝖊sh p𝖆vish𝖊nn𝖆", 
"S p𝖆vish𝖊ni𝖊m 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞u𝖞 p𝖆visl𝖆 𝖆p𝖞", 
"L𝖊xk𝖆𝖙n𝖊u k𝖆k𝖔u𝖙𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh bl𝖆kn𝖔𝖙n𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 n𝖞𝖆shn𝖞𝖞𝖔 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖞𝖈h𝖊bn𝖆 𝖆p𝖞", 
"P𝖆 pp𝖆k𝖙ik𝖊 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Z𝖆g𝖆d𝖆𝖈hn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 pp𝖆v𝖆m𝖞 𝖆p𝖞", 
"P𝖆 z𝖆k𝖔n𝖞 𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 𝖆p𝖞", 
"S𝖆s𝖊sh pipik𝖆lk𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh s𝖆s𝖞sh𝖆𝖞𝖆 𝖆p𝖞", 
"P𝖆p𝖙iz𝖆nsk𝖊 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖊n𝖞𝖆 l𝖞𝖔bi𝖙 ks𝖙𝖆𝖙𝖊 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b ppi𝖞𝖆𝖙n𝖆 s𝖆s𝖊𝖙",
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 s 𝖆bi𝖈hi𝖊m", 
"P𝖆 ppim𝖊𝖙𝖊 s𝖆ss𝖊sh p𝖆 f𝖊n sh𝖞𝖞𝖔 s𝖆s𝖊sh 𝖆p𝖞", 
"Цv𝖊𝖙𝖔𝖈hn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖆lb𝖔k𝖆u𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh v цv𝖊𝖙𝖆x 𝖆p𝖞", 
"P𝖆 p𝖆pk𝖔v𝖆𝖈hn𝖆m𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh ks𝖙 𝖆p𝖞 s𝖆s𝖊sh l𝖞𝖆g𝖞sh𝖆𝖙in𝖆 𝖆p𝖞", 
"N𝖊z𝖆biv𝖆𝖊m𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙ix𝖆 𝖙ix𝖆", 
"S𝖆s𝖊sh smi𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊m p𝖆 b𝖊spp𝖊d𝖊l𝖞 𝖆p𝖞", 
"M𝖞p𝖈h𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh gp𝖆mix𝖆𝖞𝖔sh𝖊 𝖆p𝖞", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 z𝖆𝖈h𝖊m𝖙𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆d n𝖔lb 𝖆p𝖞", 
"P𝖆 𝖞𝖙p𝖊ц𝖞 s𝖆s𝖆l𝖆 mn𝖊 𝖙v𝖆u𝖆 m𝖆mk𝖆 𝖆p𝖞", 
"𝖙𝖆k 𝖙𝖆 p𝖔s𝖆siv𝖆𝖊shb p𝖔 m𝖔𝖊m𝖞 𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖔𝖞𝖆 m𝖆𝖙b sh𝖔l𝖆v𝖆 n𝖊d𝖆p𝖆zvi𝖙𝖆𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖔m k𝖆𝖙𝖆𝖞𝖔 k𝖆l𝖆b𝖔𝖈hin𝖆 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"Z𝖆v𝖊l 𝖙v𝖔u kl𝖊𝖙𝖆p x𝖞u𝖊m 𝖙𝖊p𝖊pb 𝖔n gp𝖊mi𝖙 𝖆p𝖞", 
"Ppil𝖊pliv𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖊b𝖞 sh𝖔𝖙𝖆 l𝖊xk𝖔", 
"S𝖆s𝖊sh p𝖆 p𝖞sski", 
"K𝖆k n𝖆d𝖆 s𝖆s𝖊sh 𝖞zb𝖊𝖈hk𝖆 𝖊b𝖆n𝖆𝖞𝖆", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊sh g𝖔l𝖆𝖞𝖆", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m p𝖆 m𝖆pshin𝖆m 𝖙p𝖔g𝖆𝖞𝖔 𝖆p𝖞", 
"𝖔p𝖞𝖆𝖙b s𝖆s𝖊sh 𝖆p𝖞", 
"Igpiv𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊 𝖆p𝖞", 
"Ppizp𝖊nn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖙i mn𝖊 v x𝖞u m𝖔pg𝖆𝖊shb l𝖞𝖆g𝖞sh𝖆𝖙in𝖆 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"𝖆p𝖊g𝖊n𝖆lbn𝖆 𝖙v𝖆𝖞𝖔 m𝖆𝖙b pp𝖆sц𝖆l 𝖆p𝖞 sh𝖔𝖙𝖆", 
"Izv𝖊s𝖙n𝖆 s𝖆s𝖊sh 𝖔l𝖞x 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 ppiv𝖆𝖙𝖊zip𝖆v𝖆l 𝖆p𝖞", 
"B𝖆g𝖞p𝖙𝖞𝖆sh𝖊 s𝖆s𝖊sh 𝖆p𝖞𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖆bpig𝖆l𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙𝖊l𝖆m𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 vid𝖊pjk𝖞𝖆p𝖞", 
"S𝖆s𝖊sh mn𝖊 𝖙𝖞𝖙𝖆𝖆p𝖞", 
"Ppi vs𝖊u k𝖆nf𝖊 s𝖆s𝖊sh𝖆p𝖞", 
"S𝖆s𝖊sh d𝖞p𝖆 𝖊b𝖆n𝖆𝖞𝖆𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖞bil s𝖔p𝖊𝖆p𝖞", 
"Slish k𝖞 s𝖔s𝖊shb𝖆p𝖞", 
"Md𝖆 𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 v l𝖊xk𝖞𝖞𝖔𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆ц𝖊l𝖞𝖞𝖆mi𝖆p𝖞", 
"N𝖆 p𝖆m𝖞𝖆𝖙b 𝖙𝖞𝖆 𝖆b𝖆sц𝖆l𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 l𝖊𝖙𝖞 𝖆p𝖞", 
"P𝖆 p𝖊ц𝖊p𝖙𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"N𝖆 vix𝖆dnix s𝖆s𝖊sh 𝖆p𝖞", 
"B𝖊zm𝖊pn𝖆 s𝖆sn𝖞l𝖆 𝖙i mn𝖊 𝖆p𝖞", 
"Slish 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆m𝖞lbk𝖞 v sp𝖆k𝖆𝖙𝖆n p𝖊pd𝖔l𝖞𝖔 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"S𝖆s𝖊sh z𝖆visim𝖆 𝖆p𝖞 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s z𝖆vis𝖙b𝖞𝖔 s𝖆s𝖊𝖙 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆di b𝖔g𝖆 𝖆p𝖞 𝖆p𝖞", 
"P𝖆di 𝖆ll𝖆x𝖆 𝖙v𝖆𝖞𝖔 m𝖆𝖙b 𝖆b𝖆sц𝖆l 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖆k𝖙ivn𝖆 s𝖆s𝖊sh 𝖆p𝖞 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 sm𝖞gl𝖞𝖞𝖔 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"𝖙v𝖆u𝖆 m𝖆𝖙b s b𝖆z𝖆p𝖆 n𝖆 m𝖔u x𝖞u𝖊ц ppib𝖊j𝖆l𝖆 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖆pip𝖆𝖊𝖙s𝖆 n𝖆 m𝖔u x𝖞u k𝖆gd𝖆 vs𝖙𝖆𝖊𝖙 s d𝖊v𝖆n𝖆", 
"K𝖔gd𝖆 gi𝖙l𝖊p z𝖆v𝖔𝖊viv𝖆l m𝖔skv𝖞 𝖔n sl𝖞𝖈h𝖆un𝖔 z𝖆v𝖔𝖊v𝖆l pizd𝖆𝖈hin𝖞 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b d𝖔𝖈hb sh𝖔l𝖆vi 𝖞 v𝖆s э𝖙𝖔 n𝖆sl𝖊ds𝖙v𝖊nn𝖔𝖊 𝖙ip𝖆", 
"S𝖆s𝖊sh k𝖆k dp𝖞g 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"K𝖆k s𝖔b𝖆k𝖞 𝖙𝖞𝖆 x𝖞u𝖊m l𝖞𝖆pn𝖞l 𝖆p𝖞",
"S𝖆s𝖊sh b𝖊sp𝖆l𝖊zn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 p𝖊ц𝖊p𝖙𝖞 sv𝖆𝖊u m𝖆𝖙𝖊pi 𝖆p𝖞 𝖙𝖆k 𝖙𝖆", 
"P𝖆dl𝖊𝖈hil 𝖙𝖞𝖆 x𝖞u𝖊m 𝖆p𝖞", 
"𝖞𝖆 𝖙𝖊b𝖞𝖆 s𝖊u𝖈h𝖆s 𝖔b𝖔ss𝖞 p𝖔b𝖊jishb v ls pis𝖆𝖙b mn𝖊 pp𝖔 mip𝖔v𝖞𝖞𝖔 d𝖞p𝖆 𝖙i 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh k𝖆k in𝖆m𝖆pk𝖆 𝖆p𝖞",

"X𝖞u𝖊m 𝖙𝖞𝖆 vik𝖊n𝖞l 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 s sh𝖔l𝖆vi"
"N𝖊p𝖆b𝖊dim𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖞𝖆 v pizd𝖊 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi x𝖞u𝖊m dp𝖆uv𝖊p𝖆 p𝖊p𝖊𝖞s𝖙𝖆n𝖆vil 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 m𝖔u x𝖞u p𝖔k𝖞pi𝖙b z𝖔v𝖊𝖙", 
"𝖞𝖆 𝖙𝖊 x𝖞𝖊m pizd𝖆k p𝖆zdp𝖔bil", 
"𝖙i mn𝖊 x𝖞u 𝖙p𝖊sh 𝖞𝖆zik𝖔m", 
"𝖙v𝖔𝖞𝖆 m𝖆mk𝖆 d𝖆v𝖆lk𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆", 
"Ss𝖞 v 𝖙𝖞𝖆", 
"Sm𝖊l𝖆 s𝖆s𝖊sh", 
"K𝖆k  n𝖆d𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 m𝖔kp𝖞𝖞𝖔", 
"Jidk𝖆sn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"K𝖞p𝖞𝖔 i 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b ip𝖞 l𝖊xkl 𝖆p𝖞", 
"S𝖆s𝖊sh shl𝖊shk𝖆 𝖆p𝖞", 
"Z𝖆d𝖔pn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Gpiz𝖊shb m𝖔u x𝖞u 𝖆p𝖞", 
"S𝖆s𝖊sh ppispi𝖈hn𝖆 𝖆p𝖞", 
"Dipl𝖔m𝖆𝖙i𝖈h𝖊ski s𝖆s𝖊sh 𝖆p𝖞", 
"G𝖞m𝖆ni𝖙𝖆pn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"K𝖆k n𝖆d𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"M𝖆mk𝖞 𝖙v𝖆𝖞𝖔 n𝖆s𝖊l𝖞𝖞𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b shl𝖊shk𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 z𝖆b𝖆vn𝖆 𝖆p𝖞", 
"𝖙𝖊p𝖊bl𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m 𝖆p𝖞", 
"Bl𝖞𝖆 s𝖔s𝖊shb 𝖆p𝖞", 
"F𝖞 s𝖔s𝖊shb 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b z𝖆𝖊b𝖆n𝖆𝖞𝖆 sh𝖔l𝖆v𝖆 𝖆p𝖞", 
"M𝖆𝖙b 𝖙v𝖆𝖞𝖔 x𝖞u𝖊m p𝖆k𝖞s𝖆l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b g𝖆pi𝖙 n𝖆 m𝖆u𝖊m x𝖞u𝖞𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m issl𝖊d𝖆v𝖆l 𝖆p𝖞", 
"𝖙ix𝖆 𝖙ix𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Ppin𝖞jd𝖊nn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊sh smishn𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b l𝖊xk𝖔 s𝖆s𝖊𝖙 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 l𝖆x𝖆 𝖆p𝖞", 
"Iz𝖞𝖆shbn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"X𝖞u𝖊ц m𝖔u v𝖆flishb 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 sk𝖔p𝖔s𝖙i 𝖆p𝖞", 
"P𝖆 f𝖆k𝖙𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 gp𝖞b𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 n𝖊jn𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m shl𝖊pn𝖞l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 min𝖞𝖆 n𝖆 x𝖞u𝖞 p𝖆visl𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆𝖙shl𝖊p𝖆l 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 k𝖆p𝖆𝖞𝖔 𝖆p𝖞", 
"Bl𝖞𝖆 s𝖔s𝖊shb 𝖆p𝖞", 
"Ks𝖙𝖆𝖙𝖊 𝖙v𝖆𝖞𝖔 m𝖆𝖙b ipip𝖞𝖞𝖔 𝖆p𝖞", 
"Pp𝖆v𝖔sl𝖆vn𝖔 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"𝖊b𝖞 𝖙v𝖔u m𝖔kpiu p𝖔𝖙 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖊p𝖊v𝖊pn𝖞l 𝖆p𝖞", 
"Md𝖆 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"S l𝖊xk𝖆v𝖆 𝖙i n𝖆𝖈h𝖆l x𝖞u s𝖆s𝖆𝖙b 𝖆p𝖞", 
"Slish x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"Vv𝖊px n𝖔g𝖆mi x𝖞u s𝖆s𝖊sh 𝖆kp𝖔b𝖆𝖙 sh𝖔l𝖊 𝖆p𝖞", 
"K𝖞,ks𝖙𝖆𝖙𝖊 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"D𝖊m𝖔ni𝖈h𝖊ski 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u𝖊ц vl𝖞𝖔bl𝖊nn𝖆 dp𝖔𝖈h𝖊𝖙 md𝖆 s𝖊m𝖊un𝖆𝖊 𝖞 v𝖆s 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 p𝖆 p𝖆g𝖔d𝖊 md𝖆 md𝖆 md𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙v𝖔u p𝖆n𝖔sh𝖊𝖊iu kl𝖊𝖙𝖆p 𝖆p𝖞", 
"S𝖆s𝖊sh k𝖆k g𝖊u 𝖆p𝖞", 
"S𝖆s𝖊sh s vig𝖆d𝖆u 𝖆p𝖞", 
"P𝖞𝖆𝖙iu p𝖆z 𝖙v𝖔u p𝖔𝖙 n𝖆s𝖆dil n𝖆 x𝖞u𝖊ц 𝖆p𝖞", 
"S𝖆s𝖊sh gpim𝖞𝖆 p𝖊zd𝖔u 𝖆p𝖞", 
"Z𝖔vi m𝖆𝖙b p𝖔𝖙𝖔m s𝖔s𝖆𝖙b 𝖆p𝖞", 
"𝖞j𝖆sn𝖆 s𝖆s𝖊sh shl𝖊shk𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆pp𝖆kin𝖞l 𝖆p𝖞", 
"Db𝖞𝖆v𝖔lbski m𝖔u x𝖞u𝖊ц dp𝖔𝖈h𝖊sh 𝖆p𝖞", 
"𝖙l𝖊𝖞𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"Id𝖊𝖆lbn𝖆 𝖙i mn𝖊 vis𝖆s𝖆l𝖆 𝖆p𝖞", 
"Md𝖆 𝖙v𝖆𝖞𝖆 m𝖆𝖙b mn𝖊 z𝖆 g𝖆p𝖆mi dp𝖆𝖈hn𝖞l𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"P𝖆 k𝖔d𝖊ks𝖞 s𝖆s𝖊sh l𝖊xk𝖔 𝖆p𝖞", 
"V b𝖆pshin𝖊 𝖙𝖞𝖆 𝖊b𝖆l 𝖆p𝖞", 
"Ip𝖞 𝖙𝖞𝖆 s piv𝖆s𝖔m v p𝖞k𝖊 𝖆p𝖞", 
"Эu s𝖆s𝖊 𝖆p𝖞", 
"Z𝖆g𝖆v𝖆pil 𝖙𝖞𝖆 x𝖞𝖊m l𝖊xk𝖔 𝖆p𝖞", 
"V shk𝖔l𝖊 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆bpig𝖆l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b dimi𝖙 s m𝖆im x𝖞u𝖊m 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 v цz 𝖆p𝖞",
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b vib𝖆p𝖆𝖈hn𝖆 s𝖆s𝖊𝖙 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 n𝖆 vijiv𝖆ni𝖊 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 sh𝖆k𝖆lk𝖆 𝖆p𝖞", 
"Ks𝖙𝖆𝖙𝖊 𝖙v𝖆𝖞𝖔 m𝖆𝖙b p𝖊pd𝖔l𝖞𝖔 𝖆𝖙li𝖈hn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖊v𝖆zm𝖔jn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 𝖈h𝖊𝖙v𝖊pk𝖞 d𝖆 sv𝖆𝖊u m𝖆𝖙𝖊pi n𝖊 d𝖆𝖙𝖞𝖆n𝖞l 𝖆p𝖞", 
"G𝖊𝖔l𝖔gi𝖈h𝖊ski s𝖆s𝖊sh 𝖆p𝖞", 
"N𝖊v𝖆zm𝖔jn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 sv𝖔𝖊m𝖞 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 p𝖆dn𝖔m𝖞 𝖆p𝖞", 
"S𝖆s𝖊sh m𝖆𝖙𝖞𝖔k𝖆𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊sh gp𝖆цi𝖔zn𝖆 𝖆p𝖞", 
"N𝖊𝖞d𝖆vn𝖆v𝖊sh𝖊nn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b k𝖆z𝖆 z𝖆𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh sm𝖊𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖞d𝖔vl𝖊𝖙v𝖆p𝖊nn𝖔 𝖆p𝖞",

"S𝖆s𝖊sh m𝖊lk𝖆 𝖆p𝖞", 
"Sk𝖔p𝖆 s𝖆sn𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh m𝖆l𝖆 𝖊sh𝖊 v dv𝖆 p𝖆z𝖆 b𝖔lbsh𝖊 s𝖔s𝖆𝖙b b𝖞d𝖊shb 𝖆p𝖞", 
"F𝖞 𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖊pzsk𝖆 s𝖆s𝖊𝖙 𝖆p𝖞", 
"S𝖆s𝖊sh mil𝖊ush𝖊 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖞l𝖊vk𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh g𝖊pm𝖆fp𝖆di𝖙n𝖆 𝖆p𝖞"
"Zig𝖆u 𝖙𝖞𝖆 𝖊b𝖞 𝖆p𝖞", 
"Sgp𝖞p𝖊p𝖔v𝖆nn𝖆 s𝖆s𝖊𝖙𝖊 s𝖆 sv𝖆𝖊u m𝖆mk𝖆u 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙𝖆m𝖆𝖙n𝖆 𝖆p𝖞𝖞𝖆 𝖙𝖊 𝖙f 𝖔b𝖔ss𝖆l"
"K𝖞 s𝖆s𝖊sh 𝖈hl𝖊n", 
"𝖞𝖆 𝖙𝖊 k𝖔n𝖈hil v p𝖔p𝖞 𝖞 𝖙𝖞𝖆 m𝖆𝖙𝖔p 𝖙ip z𝖆v𝖊ls𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 s𝖔s𝖆l𝖆 m𝖔u x𝖞u z𝖆 p𝖊disk𝖞 n𝖆x𝖞u", 
"L𝖔vk𝖆 s𝖆s𝖊sh", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 pizd𝖞 b𝖊p𝖊j𝖊𝖙", 
"𝖙i 𝖞 m𝖊n𝖞𝖆 v x𝖞𝖞𝖔 spishb k𝖆k v sp𝖆lbn𝖊", 
"𝖞𝖆 𝖞 𝖙𝖞𝖆 v pizd𝖆k𝖊 𝖔𝖙l𝖔jil sv𝖆𝖞𝖔 sp𝖊pm𝖞", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m z𝖆b𝖞pil 𝖙ip b𝖞p𝖔m", 
"𝖞𝖆 𝖙𝖊 v g𝖆ls𝖙𝖞k n𝖆ss𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 𝖔d𝖊v𝖆𝖊𝖙s𝖞𝖆", 
"𝖞𝖆 𝖙𝖊 n𝖆sp𝖆l v g𝖔l𝖔v𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 s𝖆l𝖔 j𝖞𝖊𝖙 𝖈h𝖔𝖙𝖆!", 
"𝖞𝖆 𝖙𝖊 n𝖆 g𝖔l𝖔v𝖞 g𝖆nd𝖔n n𝖆𝖙𝖞𝖆n𝖞l, 𝖙ip m𝖔dnik 𝖙i", 
"V𝖔𝖞𝖔 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 𝖊b𝖞 n𝖆 iz𝖊", 
"𝖞𝖆 𝖙𝖊 g𝖔l𝖔v𝖞 x𝖞𝖊m p𝖆zbil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b v mish𝖊l𝖔vk𝖞 s m𝖔im x𝖞𝖊m p𝖔p𝖆l𝖆 ks𝖙𝖆𝖙𝖊", 
"D𝖆 𝖙i s𝖆s𝖆l mn𝖊 l𝖔x", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b v sl𝖊z𝖆x 𝖊b𝖞 s𝖞k𝖆", 
"𝖞𝖆 𝖙𝖊 gl𝖆z𝖆 x𝖞𝖊m s𝖞zil, 𝖙ip ki𝖙𝖆𝖊ц 𝖙i", 
"Sp𝖞 𝖙𝖊 n𝖆 sh𝖙𝖔pki", 
"𝖙i m𝖔u x𝖞u dp𝖆ishb p𝖙𝖔m sv𝖆𝖊u m𝖆mki", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖆𝖞𝖔 z𝖆l𝖞p𝖞 𝖞𝖆zik𝖔m xl𝖊s𝖙𝖆𝖊𝖙", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m 𝖞j𝖆lil 𝖙ip kp𝖆piv𝖔u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b shl𝖞𝖔x𝖆 p𝖆g𝖆n𝖆𝖞𝖆", 
"𝖙i mn𝖊 x𝖞u s𝖆s𝖊sh n𝖆 l𝖞𝖔d𝖞𝖆x", 
"𝖞𝖆 𝖙𝖊 v 𝖙𝖞𝖆l𝖊𝖙𝖊 b𝖞m𝖆𝖞𝖔 𝖔b𝖔ss𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b ks𝖙𝖆𝖙𝖊 𝖊sh𝖊 pizd𝖞 𝖙𝖊p𝖊bi𝖙 s m𝖔im x𝖞𝖊m v g𝖔l𝖔v𝖊", 
"𝖞𝖆 𝖞 𝖙𝖞𝖆 v pizd𝖊 x𝖞𝖊m 𝖔vs𝖞𝖆nk𝖞 sv𝖆p𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 k𝖆k 𝖞m𝖊𝖊𝖙", 
"𝖞𝖆 𝖙𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖔𝖙𝖆shil d𝖔m𝖔u 𝖙ip p𝖔k𝖔unik𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 k𝖆k 𝖔𝖙p𝖊g𝖞lip𝖔v𝖆n𝖆𝖞𝖆 sh𝖔l𝖆v𝖆", 
"𝖙i x𝖞u b𝖔lbsh𝖔u s𝖔s𝖊sh mn𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 𝖈h𝖔𝖙𝖆 p𝖔 d𝖊sh𝖊vk𝖊", 
"𝖞𝖆 𝖙𝖊 n𝖆 𝖊b𝖆l𝖔 sp𝖆l", 
"𝖞𝖆 𝖙𝖞𝖆 sp𝖊pm𝖔u s𝖔bb𝖞𝖔 v d𝖆lb 𝖞pliv𝖊shb v v𝖆gin𝖞 m𝖆mki sv𝖆𝖊u", 
"Ks𝖙𝖆𝖙i 𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔u x𝖞u 𝖙𝖊l𝖊p𝖔p𝖙ip𝖔v𝖆l𝖆sb", 
"𝖞𝖆 𝖙𝖊 x𝖞u v g𝖔l𝖔v𝖞 v𝖔𝖙kn𝖞 𝖙ip sh𝖙ik n𝖔j𝖆", 
"𝖙𝖔𝖞𝖆 m𝖆𝖙b 𝖆v𝖙𝖔m𝖆𝖙𝖔m 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 sk𝖆𝖈h𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖆v𝖙𝖔m𝖆𝖙𝖔m 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 sk𝖆𝖈h𝖊𝖙", 
"𝖙i mn𝖊 x𝖞u s𝖆s𝖊sh 𝖙ip p𝖆n𝖙𝖞𝖊shbs𝖞𝖆 p𝖊p𝖊d dp𝖞jk𝖆mi sv𝖔im 𝖊bip𝖊m", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b d𝖞x𝖔vn𝖔 m𝖔u x𝖞u s𝖔s𝖊𝖙", 
"𝖙i m𝖔i 𝖞𝖆iц𝖆 k𝖞sn𝖞l i s𝖔k s nix vis𝖆siv𝖆𝖊sh", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b d𝖆j𝖊 p𝖔sl𝖊 sm𝖊p𝖙i b𝖞d𝖊𝖙 s𝖔s𝖆𝖙b m𝖔u x𝖞u", 
"𝖞𝖆 𝖙𝖊 v g𝖔l𝖔v𝖞 x𝖞u m𝖊𝖙n𝖞l, k𝖆k dp𝖔𝖙ik v d𝖆p𝖙s𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 z𝖆sip𝖆𝖊𝖙 𝖈h𝖔𝖙𝖆", 
"S𝖆s𝖊sh p𝖆m𝖆n𝖙i𝖈hn𝖆 𝖙ip", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 m𝖔u x𝖞u n𝖆 z𝖔l𝖔𝖙𝖞𝖞𝖔 m𝖊d𝖆lb", 
"𝖞𝖆 𝖙𝖊 v sh𝖊ki n𝖆sp𝖆l, 𝖙i 𝖙ip x𝖔m𝖞𝖆k", 
"𝖙i m𝖔u x𝖞u l𝖞𝖔bishb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖊bip𝖞𝖊𝖙 m𝖔u x𝖞u sv𝖔im kl𝖊𝖙𝖆p𝖆m", 
"𝖙i m𝖔im x𝖞𝖊m g𝖞bi 𝖞vl𝖔jn𝖞𝖆𝖊shb s𝖊b𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 m𝖔u x𝖞u k𝖆k 𝖊n𝖔𝖙 𝖊b𝖆niu", 
"Sp𝖞 𝖙𝖊 v g𝖆zip𝖔vk𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖈h𝖔𝖙𝖆 z𝖆gnil𝖆 b𝖊z m𝖔𝖊g𝖔 x𝖞𝖞𝖆", 
"𝖞𝖆 𝖙𝖊b𝖊 k𝖆dik x𝖞𝖊m vip𝖔vnil i 𝖞 𝖙𝖊b𝖞𝖆 iz p𝖙𝖆 sp𝖊pm𝖆 p𝖔𝖙𝖊kl𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b z𝖆 m𝖔u x𝖞u sxv𝖆𝖙il𝖆sb k𝖔gd𝖆 n𝖆 k𝖔p𝖙𝖔𝖈hk𝖆x n𝖆 𝖞liц𝖊 sp𝖆l𝖆", 
"𝖊b𝖞 𝖙v𝖔𝖞𝖔 m𝖆𝖙b vidp𝖞 𝖊b𝖆n𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b p𝖊p𝖊sm𝖔𝖙p𝖊l𝖆 𝖞j𝖆s𝖔v i s𝖆s𝖊𝖙 𝖙𝖊pb 𝖞j𝖆sn𝖔", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m z𝖆𝖙p𝖊s 𝖙𝖆k 𝖈h𝖙𝖔 𝖙i dp𝖔j𝖆l s𝖔s𝖞𝖆 m𝖔u x𝖞u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b p𝖊p𝖊p𝖞𝖙𝖆l𝖆 piv𝖔 s m𝖔im x𝖞𝖊m i xl𝖊bn𝖞l𝖆 s𝖆nini", 
"𝖞𝖆 𝖙𝖊 x𝖞𝖊m 𝖊b𝖆l𝖔 pv𝖞 k𝖆k g𝖆z𝖊𝖙𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m f𝖞𝖙b𝖔l sm𝖔𝖙pi𝖙",

"𝖞𝖆 𝖙𝖊 x𝖞𝖊m n𝖔s 𝖞𝖙𝖊p k𝖆k 𝖙p𝖞𝖆p𝖔𝖈hk𝖔u", 
"𝖞 𝖙𝖞𝖆 m𝖔u x𝖞u v 𝖆n𝖆l𝖊 p𝖊zvi𝖙s𝖞𝖆", 
"S𝖆s𝖊sh sl𝖆dk𝖔 𝖙𝖆k", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔im x𝖞𝖊m v sv𝖔𝖞𝖔 pizd𝖞 x𝖞un𝖞𝖔 pp𝖔𝖙𝖆lkiv𝖆𝖊𝖙", 
"𝖞𝖆 pizd𝖆k 𝖙v𝖆𝖊u m𝖆𝖙𝖊pi x𝖞𝖊m vibil 𝖙𝖆k 𝖈h𝖙𝖔 s n𝖊g𝖔 𝖔shm𝖊𝖙ki sip𝖆lisb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m n𝖆 dip𝖈hik𝖊 k𝖆𝖙𝖆𝖊𝖙s𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 sh𝖆 x𝖞𝖊m 𝖙p𝖆vmip𝖞𝖞𝖔 𝖙𝖞𝖙 l𝖆sh𝖔kip𝖞 𝖙𝖞𝖆 p𝖆𝖙ix𝖔nbk𝖞 d𝖞p𝖆𝖈hk𝖆, 𝖊z 𝖊z0", 
"P𝖆 𝖙ix𝖆m𝖞 𝖙i mn𝖊 s𝖆s𝖆l𝖆 d𝖞pёx𝖆, md𝖆 𝖊z 𝖊z", 
"P𝖆 d𝖊vi𝖈h𝖊 s𝖆s𝖊sh", 
"S s𝖆m𝖆v𝖆 n𝖆𝖈h𝖆l𝖆 s𝖆s𝖊sh iz𝖊", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m shl𝖊pn𝖞l iz𝖊 iz𝖊", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞𝖆zik𝖔m m𝖔u x𝖞u pizd𝖊𝖙 iz𝖊", 
"𝖊b𝖞 𝖙v𝖆𝖞𝖔 p𝖆n𝖔sh𝖊n𝖞𝖞𝖔 m𝖆𝖙b", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 min𝖞𝖆 n𝖆 x𝖞u𝖞 kp𝖞𝖆x𝖙𝖊l𝖆", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 min𝖞𝖆 n𝖆 x𝖞u𝖞 s𝖔pli j𝖞𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊g𝖔 x𝖞𝖞𝖆 sl𝖊𝖙𝖆𝖊𝖙", 
"Sh𝖆s 𝖙v𝖔𝖞𝖔 m𝖆𝖙b pijd𝖆k𝖔m n𝖆 s𝖙𝖆𝖙𝖞𝖊 sv𝖔b𝖔di p𝖔v𝖊sh𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u dp𝖔𝖈hi𝖙", 
"𝖞𝖆 𝖙v𝖔u p𝖔𝖙 sh𝖆s x𝖞ёm sdёpn𝖞 i p𝖔pv𝖞 n𝖆x𝖞u", 
"M𝖆mk𝖞 𝖙v𝖔𝖞𝖔 𝖊b𝖞𝖙 k𝖆k vs𝖊gd𝖆", 
"𝖞𝖆 pizd𝖆k 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi x𝖞ёm p𝖊p𝖊v𝖆pil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 p𝖔pv𝖆l𝖆sb", 
"Mn𝖊 p𝖔x𝖞u, 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆m𝖞 𝖊b𝖆l эl𝖊k𝖙p𝖔n𝖆s𝖔s𝖔m", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊u z𝖆l𝖞pi p𝖊p𝖊v𝖆lil𝖆sb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b ish𝖊uk𝖆 m𝖔𝖊g𝖔 x𝖞𝖞𝖆", 
"Pil m𝖆𝖙b 𝖙v𝖔𝖞𝖔 𝖊b𝖞 k𝖆l𝖔sh𝖆mi", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b pizd𝖔u x𝖞i k𝖞pi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b v z𝖆l𝖞p𝖞 m𝖔𝖞𝖔 vpil𝖆sb", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞 n𝖆 vis𝖔𝖙𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔𝖙 p𝖊p𝖊d𝖔z𝖆 z𝖆l𝖞p p𝖔d𝖔xl𝖆", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 𝖊b𝖞 𝖞 p𝖆dik𝖆 sh𝖔l𝖆v𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔𝖙 m𝖔𝖊g𝖔 x𝖞𝖞𝖆 𝖞b𝖊jish𝖊 ishi𝖙", 
"𝖞𝖆 pizd𝖆𝖔m 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi p𝖔lbz𝖞𝖞𝖔sb k𝖆k p𝖔l𝖔v𝖔u 𝖙p𝖞𝖆pk𝖔u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b b𝖞ks𝖞𝖊𝖙 n𝖆 m𝖔𝖊m x𝖞𝖞𝖔", 
"Pizd𝖆k 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖞 mnn𝖞𝖆 v n𝖔g𝖆x v𝖔l𝖞𝖆𝖊𝖙s𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b l𝖆sk𝖆𝖊𝖙s𝖞𝖆 s m𝖔im x𝖞𝖊m", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 vs𝖙𝖆n𝖞𝖞𝖔 𝖈h𝖊l𝖞𝖔s𝖙b z𝖆bil𝖆",
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b v 𝖞𝖆uц𝖆x m𝖔ix sidi𝖙", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 z𝖆l𝖞p𝖔u bb𝖞𝖔", 
"Z𝖆p𝖞bil 𝖙𝖞𝖆 x𝖞𝖊m", 
"Ss𝖞 𝖙𝖊 v g𝖔l𝖔v𝖞", 
"Sp𝖞 𝖙𝖊 v 𝖆n𝖆l", 
"D𝖆 𝖙i g𝖞b𝖆mi s𝖆s𝖊sh", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s dv𝖞x s𝖙𝖔p𝖔n s𝖔s𝖊𝖙", 
"S𝖆s𝖊sh v𝖆lidn𝖆", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞 n𝖆 m𝖔ni𝖙𝖔p𝖊", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖔b m𝖔u x𝖞u kliki 𝖙𝖔𝖈hi𝖙", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 x𝖞𝖊m sh𝖆n𝖙𝖆jip𝖞𝖞𝖔 𝖈h𝖔𝖙𝖆", 
"Slix, sh𝖆 𝖙𝖊 j𝖆bpi 𝖔b𝖔sp𝖞", 
"P𝖆n𝖙𝖔v𝖆 s𝖆s𝖊sh 𝖙𝖆k", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b sh𝖔l𝖆v𝖆 z𝖆bi𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m s 𝖙𝖔lk𝖞 sbil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 shk𝖞p𝖞𝖆𝖙in𝖆", 
"Pin𝖆𝖞𝖔 𝖙v𝖆𝖞𝖔 𝖙𝖞𝖆nk𝖞 x𝖞im", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b ks𝖙𝖆𝖙i zp𝖊l𝖆𝖞𝖆 sh𝖔l𝖆v𝖆", 
"𝖙i mn𝖊 s𝖆s𝖊shb k𝖆k g𝖊u",
"𝖔p𝖞 s 𝖙𝖊b𝖞𝖆 n𝖆ivn𝖆𝖞𝖆 x𝖞𝖊s𝖔sk𝖆", 
"𝖞𝖆 𝖙𝖊 g𝖔l𝖔v𝖞 z𝖆l𝖞p𝖆u vikp𝖞𝖙il k𝖆k g𝖆uk𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b k𝖞piц𝖆 𝖔bъ𝖊b𝖆n𝖆𝖞𝖆", 
"Sp𝖞 𝖙𝖊 v gp𝖊b𝖊sh𝖊k", 
"V l𝖊ц𝖔 𝖙𝖊 sp𝖞 b𝖊dn𝖞𝖆g𝖆(", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞 p𝖔 sv𝖞𝖆z𝖞𝖆m", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b z𝖆l𝖞p𝖆u pin𝖆𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m x𝖔di𝖙 v ц𝖊l𝖞𝖆x s𝖆m𝖔𝖔b𝖔p𝖔ni", 
"Эu k𝖞 zd𝖆p𝖔v s𝖆s𝖊sh x𝖞u", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m p𝖊m𝖆n𝖙ip𝖞𝖞𝖔", 
"S x𝖞𝖊m m𝖆im v𝖆 p𝖙𝖞 x𝖔di𝖙 s𝖙ilb 𝖙𝖆klu 𝖈h𝖙𝖔l𝖊", 
"𝖞𝖆 𝖙𝖊 x𝖞𝖊m liц𝖔 vibil k𝖆k n𝖆dv", 
"𝖞𝖆 𝖙v𝖔𝖊u m𝖆𝖙𝖊p𝖊 x𝖞𝖊m p𝖔 𝖊𝖊 v𝖔l𝖔s𝖆𝖙𝖔u j𝖔p𝖊 s𝖙𝖞kn𝖞l s𝖞k𝖆", 
"S𝖔s𝖊sh mn𝖊 v g𝖆p𝖆j𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u v sv𝖔u 𝖈h𝖊pniu kli𝖙𝖔p s𝖞𝖊𝖙", 
"Lij𝖊shb mn𝖊 z𝖆l𝖞pk𝖞 b𝖊z э𝖙𝖆v𝖆 nik𝖆k", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 sv𝖔im n𝖊 p𝖞sskim p𝖙𝖔m", 
"𝖞𝖆 𝖙𝖊 v pizd𝖆k x𝖞𝖊m bpizg𝖆𝖞𝖔 k𝖆k b𝖆l𝖔n𝖈hik𝖆m kp𝖆ski", 
"M𝖔u x𝖞u v pizd𝖊 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖙𝖆nц𝖞𝖊𝖙 𝖙𝖆n𝖊ц d𝖔jd𝖞𝖆 s𝖞k𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 x𝖞𝖊m v b𝖊pm𝖞цk𝖆m 𝖙pi𝖞g𝖔lnik𝖊 zpm𝖞p𝖆vpl", 
"𝖞𝖆𝖙𝖞𝖆 n𝖆p𝖆il kp𝖞shk𝖆u sp𝖊pmi",

"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖆vn𝖔v𝖊si𝖊 d𝖊pji𝖙", 
"𝖙i mn𝖊 n𝖆s𝖙𝖞pil 𝖞𝖆zik𝖔m n𝖆 x𝖞u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 k𝖆k in𝖔m𝖆pk𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 z𝖆l𝖞p𝖆u k𝖆lix𝖆𝖞𝖔", 
"𝖙v𝖆𝖞𝖔 s𝖊mb𝖞𝖔 vs𝖊 𝖊b𝖞𝖙", 
"P𝖆 f𝖆n𝖆𝖙izm𝖞 s𝖆s𝖊sh", 
"𝖞𝖆 𝖙𝖊 k𝖔n𝖈h𝖙il v p𝖔𝖙 𝖙𝖞𝖆 k𝖆ndp𝖆shi𝖙 𝖙𝖊pb", 
"𝖞𝖆 𝖙𝖊 n𝖆 sh𝖙𝖆nin𝖞 sp𝖞", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m m𝖞𝖆l k𝖆k 𝖙𝖊s𝖙𝖔 𝖊b𝖆n𝖔𝖊", 
"𝖙i s m𝖆𝖊u z𝖆l𝖞p𝖆u s𝖆s𝖊shs𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖙𝖊b𝖞𝖆 v d𝖊𝖙s𝖙v𝖊 n𝖆 m𝖔u x𝖞u 𝖞p𝖔nil𝖆sh𝖔l𝖆v𝖆 s𝖆s𝖊sh mn𝖊 n𝖊d𝖊lbn𝖆", 
"S𝖙𝖆v𝖆𝖈hn𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"S𝖆s𝖊sh mn𝖊 𝖞g𝖆dliv𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 𝖞g𝖔dliv𝖆", 
"S𝖆s𝖊sh mn𝖊 mp𝖆𝖈hliv𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖆d𝖊lil", 
"𝖆gp𝖊sip𝖞𝖞𝖔 v 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Xi𝖙p𝖆 s𝖆s𝖊sh", 
"Kp𝖔𝖞𝖔sb v 𝖙𝖊 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 d𝖞sh𝖞", 
"P𝖆d𝖞jn𝖔 s𝖆s𝖊sh mn𝖊", 
"S𝖆s𝖊sh mn𝖊 b𝖊z ppi𝖈hin", 
"X𝖞u𝖊m 𝖙𝖞𝖆 s𝖆mkn𝖞l", 
"Sl𝖊𝖙𝖆𝖞𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊", 
"S𝖆sn𝖞l𝖆 i n𝖔𝖊shb d𝖞p𝖆", 
"S𝖆s𝖊sh x𝖞𝖊ц", 
"𝖞𝖆 𝖙v𝖔u p𝖔𝖙 x𝖞ёm p𝖆zx𝖞𝖞𝖆pil", 
"S𝖆s𝖊sh mn𝖊 v𝖆𝖙n𝖆", 
"M𝖔shn𝖔 s𝖆s𝖊h mn𝖊 d𝖗𝖞𝖆n", 
"𝖞𝖆 𝖙𝖊b𝖊 z𝖆l𝖞p𝖔u n𝖔s ppishimil", 
"𝖙𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊u z𝖆l𝖞pi s𝖆lb𝖙𝖔 d𝖊l𝖆𝖊𝖙", 
"𝖞𝖆 𝖙v𝖔𝖊u m𝖆mk𝖊 p𝖔dn𝖔jk𝖞 x𝖞𝖊m p𝖔ds𝖙𝖆vil 𝖔n𝖆 sl𝖔m𝖆l𝖆sb k𝖆k g𝖆m𝖞nk𝖞l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b k𝖆k pik𝖆𝖈h𝖞 vikidiv𝖆𝖞𝖔 s x𝖞𝖞𝖆 n𝖆 p𝖔l𝖊 b𝖔𝖞𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b z𝖆l𝖞p𝖔u z𝖆shiv𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b k𝖆s𝖆𝖊𝖙s𝖞𝖆 m𝖔u x𝖞u sv𝖔𝖊u pizd𝖔u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b sv𝖔i 𝖆d𝖆p𝖙𝖔pi p𝖔𝖙𝖊p𝖞𝖆l𝖆 n𝖆 m𝖔ёm x𝖞𝖞𝖔", 
"𝖞𝖆 𝖙v𝖔𝖊u m𝖆mk𝖊 𝖙𝖆z𝖔vi𝖊 k𝖔s𝖙i x𝖞𝖊m sm𝖊s𝖙il", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 sh𝖆 𝖔bp𝖞shi𝖙s𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 sh𝖆 𝖔bp𝖞shi𝖙s𝖞𝖆", 
"K𝖞 𝖊b𝖆l 𝖙𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b sv𝖆g x𝖞𝖞𝖆pi𝖙 n𝖆 m𝖔𝖊m x𝖞𝖞𝖔", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m z𝖆sh𝖞g𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖙p𝖊sn𝖞l𝖆 n𝖆 m𝖔𝖊m x𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 k𝖆lb𝖆si𝖙s𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b v m𝖔u x𝖞u 𝖞p𝖊pl𝖆sb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊g𝖔 x𝖞𝖞𝖆 𝖊b𝖆n𝖞l𝖆sb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b p𝖔s𝖔s𝖆l𝖆 x𝖞u dik𝖔 m𝖔u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔im x𝖞𝖊m dp𝖔𝖈hi𝖙s𝖞𝖆", 
"𝖞𝖆 𝖙v𝖔u p𝖔𝖙 x𝖞𝖊m dp𝖔𝖈h𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b p𝖊p𝖊d𝖔z sp𝖊pmi sl𝖔vil𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔𝖙 m𝖔𝖊g𝖔 x𝖞𝖞𝖆 sini𝖞𝖆 x𝖔di𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔𝖙 m𝖔𝖊g𝖔 x𝖞𝖞𝖆 𝖔𝖙v𝖆lil𝖆sb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 x𝖞u i v𝖊s𝖊li𝖙s𝖞𝖆 iz𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔𝖙 m𝖔𝖊g𝖔 x𝖞𝖞𝖆 𝖔𝖙biv𝖆𝖊𝖙s𝖞𝖆 p𝖞k𝖆mi 𝖊s 𝖊s", 
"V𝖔𝖞𝖆 m𝖆𝖙b d𝖊sn𝖆mi m𝖔u x𝖞u 𝖈h𝖊shi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖙p𝖆x𝖆𝖊𝖙s𝖞𝖆 s m𝖔im x𝖞𝖊m",
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b kp𝖞𝖙i𝖙s𝖞𝖆 𝖔b m𝖔u x𝖞u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 sl𝖞jb𝖞 sl𝖞ji𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b ishi𝖙 m𝖔u x𝖞u v 𝖙v𝖔ёm p𝖙𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b z𝖞bi 𝖙𝖊p𝖞𝖆𝖊𝖙 n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 iz𝖊 iz𝖊",
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b pili sv𝖔im x𝖞𝖊m z𝖆s𝖆dil", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m v z𝖊ml𝖞𝖔 vbil l𝖊xk𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b x𝖞u sh𝖆 p𝖔s𝖆s𝖆l𝖆 𝖊s 𝖊s", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔im x𝖞𝖊m shi𝖙𝖆𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖊mki pizd𝖔u sh𝖊lk𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b pili sv𝖔m x𝖞𝖊m z𝖆xv𝖆𝖙il l𝖊xk𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔bnim𝖆𝖊𝖙 m𝖔𝖞𝖔 z𝖆l𝖞p𝖞 𝖈h𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b sv𝖔𝖞𝖔 pizd𝖞 n𝖆 m𝖔u x𝖞u n𝖆m𝖆𝖙𝖆l𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b v s𝖔lnц𝖊 z𝖆shi𝖙nix 𝖔𝖈hk𝖆x m𝖔u x𝖞u s𝖔s𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖊k𝖊𝖙 m𝖔u x𝖞u pizd𝖔u sv𝖔𝖊u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b vzdp𝖔𝖈hn𝖞l𝖆 m𝖔u x𝖞u v 𝖙v𝖔𝖊m p𝖙𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊g𝖔 x𝖞𝖞𝖆 𝖆pb𝖞z 𝖊l𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 b𝖆n𝖆n j𝖞𝖊𝖙 𝖙𝖆k 𝖙𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b kid𝖆𝖊𝖙s𝖞𝖆 n𝖆 m𝖔u x𝖞u", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊g𝖔 x𝖞𝖞𝖆 p𝖆pk𝖞 𝖙v𝖔𝖊g𝖔 𝖙𝖆shil𝖆", 
"𝖞𝖆 𝖈h𝖔𝖙𝖆 𝖙v𝖔u p𝖔𝖙 vi𝖊b𝖆l n𝖆s𝖞x𝖔", 
"M𝖔u x𝖞u 𝖙v𝖔u p𝖔𝖙 k𝖆k shl𝖞𝖔x𝖞 𝖔𝖙sl𝖊dil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔i x𝖞𝖊m n𝖆𝖈h𝖆l𝖆 s p𝖔m𝖔shb𝖞𝖔 sv𝖔𝖊g𝖔 p𝖙𝖆 𝖞pp𝖆vl𝖞𝖆𝖙b",

"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊u z𝖆l𝖞pi sp𝖊pm𝖞 l𝖆k𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b is𝖙𝖊pi𝖙 n𝖆 m𝖔ёm x𝖞𝖞𝖔", 
"𝖞𝖆 sv𝖔im x𝖞ёm pizd𝖆k𝖔m 𝖙v𝖔𝖊u m𝖆mi v l𝖆p𝖙𝖞 igp𝖆𝖞𝖔", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 x𝖔d𝖞 𝖊b𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b x𝖞u m𝖔u l𝖞𝖔bi𝖙 s𝖔s𝖆𝖙b", 
"𝖞𝖆 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi x𝖞ёm ppishi d𝖆vl𝖞𝖔", 
"M𝖔u x𝖞u k𝖆k p𝖆l𝖆𝖈hb m𝖆𝖙b 𝖙v𝖔𝖞𝖔 k𝖆znil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 i b𝖊si𝖙s𝖞𝖆 shl𝖞𝖔x𝖆 gl𝖞p𝖆𝖞𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b pj𝖆v𝖞𝖞𝖔 𝖔b𝖔ss𝖆l", 
"Эu ip𝖞 𝖙v𝖆𝖞𝖔 m𝖆𝖙b 𝖙𝖆k 𝖙𝖆 , 𝖊s 𝖊s 𝖊z0", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 k𝖆k m𝖞s𝖞lbm𝖆nk𝖆, ixix 𝖊s", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 k𝖆k m𝖞s𝖞lbm𝖆nk𝖆, ixix 𝖊s", 
"N𝖆 x𝖞𝖞𝖔 pl𝖞𝖆sh𝖊shb k𝖆k djigi𝖙, 𝖆pip𝖞𝖞𝖔 𝖊s 𝖊s0l𝖆x𝖆𝖙liv𝖆𝖞𝖆 x𝖞u𝖊m 𝖙𝖞𝖆 p𝖆zb𝖊l ", 
"S𝖆s𝖊sh mn𝖊 gp𝖞b𝖆", 
"Kp𝖊𝖆𝖙ivn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 j𝖊sk𝖆", 
"B𝖊zd𝖊lbn𝖆 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖆kp𝖆b𝖆𝖙ishb n𝖆 m𝖆u𝖔m x𝖞u𝖞𝖔 ", 
"P𝖊pi𝖔d𝖆mi s𝖆s𝖊sh mn𝖊", 
"S𝖆s𝖊sh mn𝖊 v k𝖞s𝖙𝖆x", 
"X𝖞u𝖊m 𝖙𝖞𝖆 pp𝖆bil", 
"P𝖆 bl𝖆𝖙𝖞 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖆bd𝖔lbl𝖊n𝖆 s𝖆s𝖊sh mn𝖊", 
"Z𝖆l𝖊𝖙𝖊l v 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆v𝖆 ", 
"𝖙𝖞𝖆n𝖞 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Pp𝖆𝖞𝖆vils𝖞𝖆 v 𝖙𝖊 x𝖞u𝖊m", 
"P𝖞𝖙ivliv𝖆 s𝖆s𝖊sh ", 
"Ppik𝖆s𝖆𝖞𝖔sb k 𝖙𝖊 x𝖞u𝖊m sh𝖔l𝖆vn𝖆𝖞𝖆", 
"S𝖊u𝖈h𝖆s s𝖆s𝖊sh mn𝖊 ", 
"𝖔j𝖊l𝖙il 𝖙𝖞𝖆 x𝖞u𝖊m", 
"Gp𝖔mk𝖆 s𝖆s𝖊sh", 
"S𝖆s𝖊sh mn𝖊 ni𝖈h𝖙𝖔jn𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 d𝖆s𝖞𝖆g", 
"S𝖆s𝖊sh mn𝖊 x𝖞u p𝖆 bis𝖙p𝖆𝖙𝖊", 
"𝖙𝖆k𝖙𝖆 g𝖞m𝖆n𝖆 mn𝖊 s𝖆s𝖆l𝖆 𝖙i", 
"X𝖞u𝖊m n𝖆 𝖙𝖞𝖆 vz𝖆bp𝖆ls𝖞𝖆", 
"N𝖊jn𝖆 s𝖆s𝖊sh mn𝖊", 
"𝖊p𝖞 𝖙𝖞𝖆 v n𝖔s", 
"S𝖆s𝖊sh mn𝖊 v visi", 
"𝖞sh𝖆𝖙𝖆l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖙𝖆pl𝖞𝖔", 
"𝖔𝖙pip𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"S𝖆s𝖊sh mn𝖊 x𝖞u d𝖞p𝖆vliv𝖆𝖞𝖆", 
"𝖙𝖊pzn𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"𝖆𝖙li𝖈hn𝖆 s𝖆s𝖊sh mn𝖊", 
"Ppiц𝖊lbn𝖆 𝖙𝖞𝖆 𝖊p𝖞", 
"P𝖆 p𝖆p𝖙iz𝖆nski 𝖊p𝖞 𝖙𝖞𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 z𝖆mkn𝖞l", 
"𝖆p𝖙imizmi𝖈hn𝖆 s𝖆s𝖊sh", 
"V p𝖆s𝖆dk𝖊 𝖊p𝖞 𝖙𝖞𝖆", 
"𝖙v𝖆u𝖞𝖆 m𝖆mk𝖆 s𝖆s𝖆l𝖆 mn𝖊 𝖙𝖆k𝖙𝖆", 
"V p𝖔𝖙 𝖙𝖞𝖆 𝖊p𝖞 sh𝖔l𝖆vi𝖙𝖆𝖞𝖆", 
"S𝖆s𝖊sh mn𝖊 x𝖞u", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m p𝖆dm𝖊l", 
"𝖞x𝖔dishb 𝖔𝖙 x𝖞u𝖞𝖆 m𝖆𝖊g𝖔 l𝖊xk𝖔", 
"S𝖆s𝖊sh b𝖊z 𝖞v𝖆j𝖊ni𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 k𝖆k x𝖆𝖈h𝖞", 
"S𝖆s𝖊sh s d𝖆s𝖙𝖔ins𝖙v𝖆m", 
"S𝖆s𝖊sh b𝖊z pp𝖆v𝖆 n𝖆 𝖆shibk𝖞", 
"S𝖆s𝖊sh k𝖆k sh𝖔l𝖆v𝖆", 
"S𝖆s𝖊sh 𝖆𝖙li𝖈hn𝖆", 
"S𝖆s𝖊sh n𝖆 p𝖞𝖆𝖙b s pl𝖞𝖔s𝖆m", 
"S𝖆s𝖊sh k𝖆k n𝖞jn𝖔", 
"S𝖆s𝖊sh v d𝖆nniu m𝖔m𝖊n𝖙", 
"S𝖆s𝖊sh k𝖔gd𝖆 z𝖆x𝖔𝖈h𝖊shb", 
"S𝖆s𝖊sh sv𝖔im m𝖔u x𝖞u", 
"S𝖆sip𝖞𝖊sh n𝖊 pl𝖔x𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖈h𝖊kn𝖞l", 
"𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖞 d𝖞pn𝖞𝖞𝖔", 
" n𝖆k𝖆n𝖈h𝖆l v 𝖙𝖞𝖆 sh𝖆b𝖔ld𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kp𝖞𝖈h𝖞 gd𝖊 x𝖆𝖈h𝖞", 
"D𝖞p𝖆 s𝖆s𝖊sh 𝖈h𝖊𝖙k𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 p𝖆ds𝖔sn𝖞𝖞𝖔", 
"X𝖞𝖊m 𝖙𝖞𝖆 vib𝖊l", 
"Iz𝖊 s𝖆sn𝖞l𝖆 mn𝖊 sl𝖊𝖙𝖆𝖞𝖆", 
"Ppiv𝖞𝖆z𝖆n𝖆 k m𝖔𝖊m𝖞 x𝖞u𝖞𝖔 sh𝖔l𝖆vn𝖆𝖞𝖆", 
"Pp𝖊v𝖞𝖆z𝖆l𝖆s𝖞𝖆 m𝖆im x𝖞u𝖊m", 
"X𝖞𝖊m 𝖙𝖞𝖆 p𝖆m𝖞𝖆l d𝖞pn𝖞𝖞𝖔", 
"Mn𝖞 𝖙𝖞𝖆 x𝖞u𝖊m sh𝖔l𝖆vn𝖆𝖞𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖞pp𝖞𝖆𝖙𝖆l iz𝖊", 
"Pp𝖞𝖆𝖈h𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m x𝖊x𝖊", 
"P𝖆x𝖆𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m", 
"X𝖞d𝖊𝖊shb m𝖆im x𝖞u𝖊m d𝖞pn𝖆𝖞𝖆", 
"X𝖞𝖊m m𝖔im x𝖞𝖊d𝖊shb 𝖊z 𝖊z", 
"S𝖆s𝖊sh nil𝖔vk𝖆",
"S𝖆s𝖊sh p𝖔vn𝖆", 
"S𝖆s𝖊sh m𝖊𝖙k𝖆", 
"K𝖆n𝖙𝖞zil 𝖙𝖞𝖆 sv𝖔𝖊𝖖 z𝖆l𝖞p𝖔u", 
"S𝖆s𝖊sh 𝖆d𝖊kv𝖆𝖙n𝖆", 
"S𝖆s𝖊sh 𝖆s𝖙p𝖔𝖞mn𝖆", 
"S𝖆s𝖊sh gd𝖊 𝖞g𝖔dn𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 x𝖆p𝖆sh𝖔", 
"𝖊p𝖞 𝖙𝖞𝖆 m𝖊𝖙k𝖆", 
"V shif𝖗𝖊 𝖊b𝖆l 𝖙𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 k𝖆k n𝖆d𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 p𝖔 x𝖞u𝖊m iz𝖊 𝖙𝖆k𝖙𝖆", 
"𝖙𝖆k 𝖙𝖆 𝖙i mn𝖊 𝖙𝖞𝖙 s𝖔𝖔 d𝖊l𝖆𝖊sh", 
"𝖊p𝖞 𝖙𝖞𝖆 𝖆d𝖊kv𝖆𝖙n𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 n𝖆 k𝖆n𝖊", 
"S𝖆s𝖊sh mn𝖊 n𝖆 k𝖆n𝖊", 
"S𝖆𝖙k𝖞 jm𝖊shb n𝖆 x𝖞𝖊 m𝖔𝖊m", 
"K𝖞pish m𝖔u x𝖞u", 
"K𝖞pn𝖞l m𝖔u x𝖞u iz𝖊", 
"Vin𝖊s 𝖙𝖞𝖆 x𝖞u𝖊m sv𝖆im", 
"Iz𝖊 s𝖆s𝖊sh d𝖞p𝖆 sl𝖊𝖙𝖆𝖞𝖆", 
"N𝖊z𝖆biv𝖆𝖊m𝖆 s𝖆s𝖊sh", 
"S𝖆s𝖊sh b𝖊z p𝖆m𝖞𝖆𝖙i", 
"X𝖞𝖊m 𝖙𝖞𝖆 kp𝖞𝖙n𝖞l", 
"M𝖊𝖙n𝖞l v 𝖙𝖞𝖆 sv𝖔u x𝖞u", 
"Sv𝖔u x𝖞u 𝖙𝖊 m𝖊𝖙n𝖞l",
"S𝖆s𝖊sh b𝖊z s𝖔v𝖊s𝖙i", 
"B𝖊ss𝖔v𝖊s𝖙n𝖆 s𝖔s𝖊sh",

"S𝖆s𝖊sh 𝖆bikn𝖆v𝖊n𝖆", 
"Kpikliv𝖆 s𝖆s𝖊sh", 
"X𝖞u𝖊m 𝖙𝖞𝖆 vim𝖆𝖙𝖆l", 
"Vim𝖆𝖙n𝖞l 𝖙𝖞𝖆 x𝖞u𝖊m", 
"D𝖔lbishbs𝖞𝖆 𝖔b m𝖔u x𝖞u", 
"V n𝖔s 𝖙𝖊 sц𝖞", 
"V s𝖊pd𝖊𝖈hk𝖔 𝖙v𝖔ё sц𝖞", 
"N𝖆 g𝖔l𝖔v𝖞 𝖙𝖊 p𝖔s𝖆l", 
"𝖊b𝖞 𝖙𝖞𝖆 v z𝖞b", 
"X𝖞𝖊m 𝖙𝖊 z𝖞b vibil", 
"L𝖆𝖞𝖆 s𝖔s𝖊sh", 
"Z𝖆ik𝖆𝖊shbs𝖞𝖆 m𝖔im x𝖞u𝖊m", 
"Sh𝖔l𝖆vn𝖆𝖞𝖆 sц𝖞 𝖙𝖊 v p𝖊sd𝖞", 
"S m𝖔im x𝖞u𝖊m sh𝖆pil𝖞𝖆v𝖊sh sl𝖊𝖙𝖆𝖞𝖆", 
"𝖊p𝖞 𝖙𝖞𝖆 iz𝖊",
"S𝖆s𝖊sh mn𝖊 dik𝖆zn𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 izm𝖞𝖆l", 
"S𝖆s𝖊sh mn𝖊 ni𝖈h𝖙𝖔jn𝖆", 
"S𝖆s𝖊sh mn𝖊 p𝖔 m𝖆𝖙𝖊pinsk𝖊", 
"X𝖞u𝖊m n𝖆 𝖙𝖞𝖆 n𝖆b𝖊j𝖆l", 
"K𝖆p𝖆𝖞𝖔 v 𝖙𝖞𝖆 sp𝖊pm𝖆u sh𝖔l𝖆v𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 pp𝖆d𝖊pj𝖆l", 
"S𝖆s𝖊sh mn𝖊 n𝖊jn𝖆 x𝖊x𝖊", 
"𝖊p𝖞 𝖙𝖞𝖆 v n𝖆s𝖔v𝖞𝖞𝖔", 
"S𝖆s𝖊sh 𝖆bxv𝖆𝖙n𝖆", 
"X𝖞u𝖊m 𝖙𝖞𝖆 sv𝖞𝖆z𝖆l", 
"X𝖞u𝖊m 𝖙𝖞𝖆 kp𝖔s𝖞𝖔", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 p𝖊shk𝖆", 
"Sh𝖊lk𝖆vis𝖙𝖆 s𝖆s𝖊sh ", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖊bp𝖞𝖞𝖔",

"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 m𝖔u x𝖞u p𝖔k𝖞pi𝖙b z𝖔v𝖊𝖙", 
"𝖞𝖆 𝖙𝖊 x𝖞𝖊m pizd𝖆k p𝖆zdp𝖔bil", 
"𝖙i mn𝖊 x𝖞u 𝖙p𝖊sh 𝖞𝖆zik𝖔m", 
"𝖙v𝖔𝖞𝖆 m𝖆mk𝖆 d𝖆v𝖆lk𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆", 
"Ss𝖞 v 𝖙𝖞𝖆", 
"Sm𝖊l𝖆 s𝖆s𝖊sh", 
"K𝖆k  n𝖆d𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 m𝖔kp𝖞𝖞𝖔", 
"Jidk𝖆sn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"K𝖞p𝖞𝖔 i 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b ip𝖞 l𝖊xkl 𝖆p𝖞", 
"S𝖆s𝖊sh shl𝖊shk𝖆 𝖆p𝖞", 
"Z𝖆d𝖔pn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Gpiz𝖊shb m𝖔u x𝖞u 𝖆p𝖞", 
"S𝖆s𝖊sh ppispi𝖈hn𝖆 𝖆p𝖞", 
"Dipl𝖔m𝖆𝖙i𝖈h𝖊ski s𝖆s𝖊sh 𝖆p𝖞", 
"G𝖞m𝖆ni𝖙𝖆pn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"K𝖆k n𝖆d𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"M𝖆mk𝖞 𝖙v𝖆𝖞𝖔 n𝖆s𝖊l𝖞𝖞𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b shl𝖊shk𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 z𝖆b𝖆vn𝖆 𝖆p𝖞", 
"𝖙𝖊p𝖊bl𝖞𝖔 𝖙𝖞𝖆 x𝖞u𝖊m 𝖆p𝖞", 
"Bl𝖞𝖆 s𝖔s𝖊shb 𝖆p𝖞", 
"F𝖞 s𝖔s𝖊shb 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b z𝖆𝖊b𝖆n𝖆𝖞𝖆 sh𝖔l𝖆v𝖆 𝖆p𝖞", 
"M𝖆𝖙b 𝖙v𝖆𝖞𝖔 x𝖞u𝖊m p𝖆k𝖞s𝖆l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b g𝖆pi𝖙 n𝖆 m𝖆u𝖊m x𝖞u𝖞𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m issl𝖊d𝖆v𝖆l 𝖆p𝖞", 
"𝖙ix𝖆 𝖙ix𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Ppin𝖞jd𝖊nn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊sh smishn𝖔 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b l𝖊xk𝖔 s𝖆s𝖊𝖙 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 l𝖆x𝖆 𝖆p𝖞", 
"Iz𝖞𝖆shbn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"X𝖞u𝖊ц m𝖔u v𝖆flishb 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 sk𝖔p𝖔s𝖙i 𝖆p𝖞", 
"P𝖆 f𝖆k𝖙𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 gp𝖞b𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 n𝖊jn𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m shl𝖊pn𝖞l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 min𝖞𝖆 n𝖆 x𝖞u𝖞 p𝖆visl𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆𝖙shl𝖊p𝖆l 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 k𝖆p𝖆𝖞𝖔 𝖆p𝖞", 
"Bl𝖞𝖆 s𝖔s𝖊shb 𝖆p𝖞", 
"Ks𝖙𝖆𝖙𝖊 𝖙v𝖆𝖞𝖔 m𝖆𝖙b ipip𝖞𝖞𝖔 𝖆p𝖞", 
"Pp𝖆v𝖔sl𝖆vn𝖔 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"𝖊b𝖞 𝖙v𝖔u m𝖔kpiu p𝖔𝖙 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 p𝖊p𝖊v𝖊pn𝖞l 𝖆p𝖞", 
"Md𝖆 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"S l𝖊xk𝖆v𝖆 𝖙i n𝖆𝖈h𝖆l x𝖞u s𝖆s𝖆𝖙b 𝖆p𝖞", 
"Slish x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"Vv𝖊px n𝖔g𝖆mi x𝖞u s𝖆s𝖊sh 𝖆kp𝖔b𝖆𝖙 sh𝖔l𝖊 𝖆p𝖞", 
"K𝖞,ks𝖙𝖆𝖙𝖊 x𝖞u s𝖆s𝖊sh 𝖆p𝖞", 
"D𝖊m𝖔ni𝖈h𝖊ski 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u𝖊ц vl𝖞𝖔bl𝖊nn𝖆 dp𝖔𝖈h𝖊𝖙 md𝖆 s𝖊m𝖊un𝖆𝖊 𝖞 v𝖆s 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 p𝖆 p𝖆g𝖔d𝖊 md𝖆 md𝖆 md𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙v𝖔u p𝖆n𝖔sh𝖊𝖊iu kl𝖊𝖙𝖆p 𝖆p𝖞", 
"S𝖆s𝖊sh k𝖆k g𝖊u 𝖆p𝖞", 
"S𝖆s𝖊sh s vig𝖆d𝖆u 𝖆p𝖞", 
"P𝖞𝖆𝖙iu p𝖆z 𝖙v𝖔u p𝖔𝖙 n𝖆s𝖆dil n𝖆 x𝖞u𝖊ц 𝖆p𝖞", 
"S𝖆s𝖊sh gpim𝖞𝖆 p𝖊zd𝖔u 𝖆p𝖞", 
"Z𝖔vi m𝖆𝖙b p𝖔𝖙𝖔m s𝖔s𝖆𝖙b 𝖆p𝖞", 
"𝖞j𝖆sn𝖆 s𝖆s𝖊sh shl𝖊shk𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆pp𝖆kin𝖞l 𝖆p𝖞", 
"Db𝖞𝖆v𝖔lbski m𝖔u x𝖞u𝖊ц dp𝖔𝖈h𝖊sh 𝖆p𝖞", 
"𝖙l𝖊𝖞𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"Id𝖊𝖆lbn𝖆 𝖙i mn𝖊 vis𝖆s𝖆l𝖆 𝖆p𝖞", 
"Md𝖆 𝖙v𝖆𝖞𝖆 m𝖆𝖙b mn𝖊 z𝖆 g𝖆p𝖆mi dp𝖆𝖈hn𝖞l𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"P𝖆 k𝖔d𝖊ks𝖞 s𝖆s𝖊sh l𝖊xk𝖔 𝖆p𝖞"
"V b𝖆pshin𝖊 𝖙𝖞𝖆 𝖊b𝖆l 𝖆p𝖞"
"Ip𝖞 𝖙𝖞𝖆 s piv𝖆s𝖔m v p𝖞k𝖊 𝖆p𝖞", 
"Эu s𝖆s𝖊 𝖆p𝖞", 
"Z𝖆g𝖆v𝖆pil 𝖙𝖞𝖆 x𝖞𝖊m l𝖊xk𝖔 𝖆p𝖞", 
"V shk𝖔l𝖊 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖆bpig𝖆l 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b dimi𝖙 s m𝖆im x𝖞u𝖊m 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 v цz 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b vib𝖆p𝖆𝖈hn𝖆 s𝖆s𝖊𝖙 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 n𝖆 vijiv𝖆ni𝖊 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 sh𝖆k𝖆lk𝖆 𝖆p𝖞", 
"Ks𝖙𝖆𝖙𝖊 𝖙v𝖆𝖞𝖔 m𝖆𝖙b p𝖊pd𝖔l𝖞𝖔 𝖆𝖙li𝖈hn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖊v𝖆zm𝖔jn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 𝖈h𝖊𝖙v𝖊pk𝖞 d𝖆 sv𝖆𝖊u m𝖆𝖙𝖊pi n𝖊 d𝖆𝖙𝖞𝖆n𝖞l 𝖆p𝖞", 
"G𝖊𝖔l𝖔gi𝖈h𝖊ski s𝖆s𝖊sh 𝖆p𝖞", 
"N𝖊v𝖆zm𝖔jn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 sv𝖔𝖊m𝖞 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 p𝖆dn𝖔m𝖞 𝖆p𝖞", 
"S𝖆s𝖊sh m𝖆𝖙𝖞𝖔k𝖆𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊sh gp𝖆цi𝖔zn𝖆 𝖆p𝖞", 
"N𝖊𝖞d𝖆vn𝖆v𝖊sh𝖊nn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b k𝖆z𝖆 z𝖆𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh sm𝖊𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖞d𝖔vl𝖊𝖙v𝖆p𝖊nn𝖔 𝖆p𝖞", 
"S𝖆s𝖊sh m𝖊lk𝖆 𝖆p𝖞", 
"Sk𝖔p𝖆 s𝖆sn𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh m𝖆l𝖆 𝖊sh𝖊 v dv𝖆 p𝖆z𝖆 b𝖔lbsh𝖊 s𝖔s𝖆𝖙b b𝖞d𝖊shb 𝖆p𝖞", 
"F𝖞 𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖊pzsk𝖆 s𝖆s𝖊𝖙 𝖆p𝖞",

"S𝖆s𝖊sh mil𝖊ush𝖊 𝖆p𝖞", 
"S𝖆s𝖊sh n𝖞l𝖊vk𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh g𝖊pm𝖆fp𝖆di𝖙n𝖆 𝖆p𝖞", 
"Zig𝖆u 𝖙𝖞𝖆 𝖊b𝖞 𝖆p𝖞", 
"Sgp𝖞p𝖊p𝖔v𝖆nn𝖆 s𝖆s𝖊𝖙𝖊 s𝖆 sv𝖆𝖊u m𝖆mk𝖆u 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙𝖆m𝖆𝖙n𝖆 𝖆p𝖞", 
"P𝖆 𝖈h𝖊pn𝖆m𝖞 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"G𝖆p𝖙𝖆nb𝖞𝖔 s𝖆s𝖊sh 𝖆p𝖞", 
"Mipn𝖆 𝖊b𝖞 𝖙𝖞𝖆 p𝖆 n𝖔v𝖆u 𝖙𝖆k 𝖙𝖆", 
"S𝖆s𝖊sh p𝖆vish𝖊nn𝖆", 
"S p𝖆vish𝖊ni𝖊m 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞u𝖞 p𝖆visl𝖆 𝖆p𝖞", 
"L𝖊xk𝖆𝖙n𝖊u k𝖆k𝖔u𝖙𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh bl𝖆kn𝖔𝖙n𝖆 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 n𝖞𝖆shn𝖞𝖞𝖔 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖞𝖈h𝖊bn𝖆 𝖆p𝖞", 
"P𝖆 pp𝖆k𝖙ik𝖊 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"Z𝖆g𝖆d𝖆𝖈hn𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 pp𝖆v𝖆m𝖞 𝖆p𝖞", 
"P𝖆 z𝖆k𝖔n𝖞 𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 𝖆p𝖞", 
"S𝖆s𝖊sh pipik𝖆lk𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh s𝖆s𝖞sh𝖆𝖞𝖆 𝖆p𝖞", 
"P𝖆p𝖙iz𝖆nsk𝖊 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b m𝖊n𝖞𝖆 l𝖞𝖔bi𝖙 ks𝖙𝖆𝖙𝖊 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b ppi𝖞𝖆𝖙n𝖆 s𝖆s𝖊𝖙", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊𝖙 s 𝖆bi𝖈hi𝖊m", 
"P𝖆 ppim𝖊𝖙𝖊 s𝖆ss𝖊sh p𝖆 f𝖊n sh𝖞𝖞𝖔 s𝖆s𝖊sh 𝖆p𝖞", 
"Цv𝖊𝖙𝖔𝖈hn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖆lb𝖔k𝖆u𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh v цv𝖊𝖙𝖆x 𝖆p𝖞", 
"P𝖆 p𝖆pk𝖔v𝖆𝖈hn𝖆m𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh ks𝖙 𝖆p𝖞 s𝖆s𝖊sh l𝖞𝖆g𝖞sh𝖆𝖙in𝖆 𝖆p𝖞", 
"N𝖊z𝖆biv𝖆𝖊m𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙ix𝖆 𝖙ix𝖆", 
"S𝖆s𝖊sh smi𝖞𝖆sb 𝖆p𝖞", 
"S𝖆s𝖊m p𝖆 b𝖊spp𝖊d𝖊l𝖞 𝖆p𝖞", 
"M𝖞p𝖈h𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"S𝖆s𝖊sh gp𝖆mix𝖆𝖞𝖔sh𝖊 𝖆p𝖞", 
"S𝖆s𝖆l𝖆 𝖙i mn𝖊 z𝖆𝖈h𝖊m𝖙𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆d n𝖔lb 𝖆p𝖞", 
"P𝖆 𝖞𝖙p𝖊ц𝖞 s𝖆s𝖆l𝖆 mn𝖊 𝖙v𝖆u𝖆 m𝖆mk𝖆 𝖆p𝖞", 
"𝖙𝖆k 𝖙𝖆 p𝖔s𝖆siv𝖆𝖊shb p𝖔 m𝖔𝖊m𝖞 𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖔𝖞𝖆 m𝖆𝖙b sh𝖔l𝖆v𝖆 n𝖊d𝖆p𝖆zvi𝖙𝖆𝖞𝖆 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖔m k𝖆𝖙𝖆𝖞𝖔 k𝖆l𝖆b𝖔𝖈hin𝖆 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"Z𝖆v𝖊l 𝖙v𝖔u kl𝖊𝖙𝖆p x𝖞u𝖊m 𝖙𝖊p𝖊pb 𝖔n gp𝖊mi𝖙 𝖆p𝖞", 
"Ppil𝖊pliv𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖊b𝖞 sh𝖔𝖙𝖆 l𝖊xk𝖔"
"S𝖆s𝖊sh p𝖆 p𝖞sski", 
"K𝖆k n𝖆d𝖆 s𝖆s𝖊sh 𝖞zb𝖊𝖈hk𝖆 𝖊b𝖆n𝖆𝖞𝖆"
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s𝖆s𝖊sh g𝖔l𝖆𝖞𝖆", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m p𝖆 m𝖆pshin𝖆m 𝖙p𝖔g𝖆𝖞𝖔 𝖆p𝖞", 
"𝖔p𝖞𝖆𝖙b s𝖆s𝖊sh 𝖆p𝖞", 
"Igpiv𝖆 s𝖆s𝖆l𝖆 𝖙i mn𝖊 𝖆p𝖞", 
"Ppizp𝖊nn𝖆 𝖊b𝖞 𝖙𝖞𝖆 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖙i mn𝖊 v x𝖞u m𝖔pg𝖆𝖊shb l𝖞𝖆g𝖞sh𝖆𝖙in𝖆 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"𝖆p𝖊g𝖊n𝖆lbn𝖆 𝖙v𝖆𝖞𝖔 m𝖆𝖙b pp𝖆sц𝖆l 𝖆p𝖞 sh𝖔𝖙𝖆", 
"Izv𝖊s𝖙n𝖆 s𝖆s𝖊sh 𝖔l𝖞x 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 ppiv𝖆𝖙𝖊zip𝖆v𝖆l 𝖆p𝖞", 
"B𝖆g𝖞p𝖙𝖞𝖆sh𝖊 s𝖆s𝖊sh 𝖆p𝖞𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 𝖆bpig𝖆l𝖆p𝖞", 
"S𝖆s𝖊sh 𝖙𝖊l𝖆m𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 vid𝖊pjk𝖞𝖆p𝖞", 
"S𝖆s𝖊sh mn𝖊 𝖙𝖞𝖙𝖆𝖆p𝖞", 
"Ppi vs𝖊u k𝖆nf𝖊 s𝖆s𝖊sh𝖆p𝖞", 
"S𝖆s𝖊sh d𝖞p𝖆 𝖊b𝖆n𝖆𝖞𝖆𝖆p𝖞", 
"Bl𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞u𝖊m 𝖞bil s𝖔p𝖊𝖆p𝖞", 
"Slish k𝖞 s𝖔s𝖊shb𝖆p𝖞", 
"Md𝖆 𝖆b𝖆sц𝖆l 𝖙𝖞𝖆 v l𝖊xk𝖞𝖞𝖔𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆ц𝖊l𝖞𝖞𝖆mi𝖆p𝖞", 
"N𝖆 p𝖆m𝖞𝖆𝖙b 𝖙𝖞𝖆 𝖆b𝖆sц𝖆l𝖆p𝖞", 
"S𝖆s𝖊sh n𝖆 l𝖊𝖙𝖞 𝖆p𝖞", 
"P𝖆 p𝖊ц𝖊p𝖙𝖞 s𝖆s𝖊sh 𝖆p𝖞", 
"N𝖆 vix𝖆dnix s𝖆s𝖊sh 𝖆p𝖞", 
"B𝖊zm𝖊pn𝖆 s𝖆sn𝖞l𝖆 𝖙i mn𝖊 𝖆p𝖞", 
"Slish 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆m𝖞lbk𝖞 v sp𝖆k𝖆𝖙𝖆n p𝖊pd𝖔l𝖞𝖔 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"S𝖆s𝖊sh z𝖆visim𝖆 𝖆p𝖞 𝖆p𝖞", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b s z𝖆vis𝖙b𝖞𝖔 s𝖆s𝖊𝖙 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆di b𝖔g𝖆 𝖆p𝖞 𝖆p𝖞", 
"P𝖆di 𝖆ll𝖆x𝖆 𝖙v𝖆𝖞𝖔 m𝖆𝖙b 𝖆b𝖆sц𝖆l 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖆k𝖙ivn𝖆 s𝖆s𝖊sh 𝖆p𝖞 𝖆p𝖞", 
"𝖊b𝖞 𝖙𝖞𝖆 sm𝖞gl𝖞𝖞𝖔 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"𝖙v𝖆u𝖆 m𝖆𝖙b s b𝖆z𝖆p𝖆 n𝖆 m𝖔u x𝖞u𝖊ц ppib𝖊j𝖆l𝖆 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔", 
"𝖙v𝖆𝖞𝖆 m𝖆𝖙b 𝖆pip𝖆𝖊𝖙s𝖆 n𝖆 m𝖔u x𝖞u k𝖆gd𝖆 vs𝖙𝖆𝖊𝖙 s d𝖊v𝖆n𝖆", 
"K𝖔gd𝖆 gi𝖙l𝖊p z𝖆v𝖔𝖊viv𝖆l m𝖔skv𝖞 𝖔n sl𝖞𝖈h𝖆un𝖔 z𝖆v𝖔𝖊v𝖆l pizd𝖆𝖈hin𝖞 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖙𝖆k 𝖙𝖆 𝖆p𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b d𝖔𝖈hb sh𝖔l𝖆vi 𝖞 v𝖆s э𝖙𝖔 n𝖆sl𝖊ds𝖙v𝖊nn𝖔𝖊 𝖙ip𝖆", 
"S𝖆s𝖊sh k𝖆k dp𝖞g 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔 𝖆p𝖞", 
"K𝖆k s𝖔b𝖆k𝖞 𝖙𝖞𝖆 x𝖞u𝖊m l𝖞𝖆pn𝖞l 𝖆p𝖞",
"S𝖆s𝖊sh b𝖊sp𝖆l𝖊zn𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh p𝖆 p𝖊ц𝖊p𝖙𝖞 sv𝖆𝖊u m𝖆𝖙𝖊pi 𝖆p𝖞 𝖙𝖆k 𝖙𝖆",

"P𝖆dl𝖊𝖈hil 𝖙𝖞𝖆 x𝖞u𝖊m 𝖆p𝖞", 
"𝖞𝖆 𝖙𝖊b𝖞𝖆 s𝖊u𝖈h𝖆s 𝖔b𝖔ss𝖞 p𝖔b𝖊jishb v ls pis𝖆𝖙b mn𝖊 pp𝖔 mip𝖔v𝖞𝖞𝖔 d𝖞p𝖆 𝖙i 𝖊b𝖆n𝖆𝖞𝖆 𝖆p𝖞", 
"S𝖆s𝖊sh k𝖆k in𝖆m𝖆pk𝖆 𝖆p𝖞", 
"X𝖞u𝖊m 𝖙𝖞𝖆 vik𝖊n𝖞l 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 s sh𝖔l𝖆vi", 
"N𝖊p𝖆b𝖊dim𝖆 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖞𝖆 v pizd𝖊 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi x𝖞u𝖊m dp𝖆uv𝖊p𝖆 p𝖊p𝖊𝖞s𝖙𝖆n𝖆vil 𝖆p𝖞 𝖙𝖆k 𝖙𝖆 l𝖊xk𝖔", 
"S𝖆s𝖊sh v p𝖔lbz𝖞 𝖆p𝖞", 
"V𝖆 dv𝖆p𝖊 s𝖆s𝖊sh 𝖆p𝖞", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 g𝖞b𝖞 𝖔𝖙 sn𝖊g𝖆 x𝖞u𝖊m 𝖆b𝖙p𝖞sil 𝖆p𝖞", 
"M𝖆𝖙b sh𝖔l𝖆v𝖆 𝖊b𝖞𝖈h𝖆𝖞𝖆 x𝖞u s𝖔sё𝖙", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 𝖈h𝖔𝖙𝖆 𝖊b𝖞 sm𝖆p𝖙fi𝖔n𝖆mi",
"𝖈h𝖔𝖙𝖆 m𝖆𝖙b 𝖙v𝖔𝖞𝖔 v 𝖙𝖊l𝖊f𝖔nn𝖔u b𝖞dk𝖊 𝖊b𝖆l x𝖊x", 
"𝖈h𝖔 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞 𝖆 n𝖊 p𝖔dsk𝖆j𝖊shb", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 𝖈h𝖔𝖙𝖆 pil 𝖊b𝖞 p𝖔d klipi 𝖙im𝖆𝖙i x𝖊x", 
"M𝖆𝖙b 𝖙v𝖔b 𝖊b𝖆l v цig𝖆nsk𝖔u 𝖙𝖆p𝖆p𝖊 𝖆v𝖊pin𝖆", 
"𝖔 m𝖆𝖙b 𝖙v𝖔𝖞𝖆 n𝖆 m𝖔ёm x𝖞𝖞𝖔 x𝖔p𝖔sh𝖔 sidi𝖙 s4k𝖆", 
"Ppis𝖔𝖊d𝖊n𝖞𝖆us𝖞𝖆 k sv𝖔𝖊u m𝖆m𝖊 m𝖔u 𝖞xu s𝖔s𝖆𝖙b", 
"M𝖆m𝖞 𝖙v𝖔b𝖞𝖔 𝖊b𝖞 n𝖆m𝖆n𝖆 𝖙𝖆k p𝖔k𝖆 𝖈h𝖙𝖔 𝖙i pl𝖆𝖈h𝖊shb x𝖊x", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 𝖊b𝖞 v p𝖔𝖙𝖆n k𝖊k", 
"X𝖞𝖊s𝖔s 𝖞𝖆 pil 𝖙v𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞", 
"X𝖞𝖊s𝖔s 𝖙i 𝖞𝖊b𝖔k n𝖆x𝖞u 𝖞𝖆 sh𝖆s 𝖙v𝖔𝖞𝖔 m𝖆𝖙b pp𝖔d𝖆m", 
"X𝖞𝖊s𝖔s 𝖞𝖆 𝖙v𝖔𝖊g𝖔 𝖔𝖙ц𝖆 𝖊g𝖔 p𝖙𝖔m k𝖆𝖙𝖆l n𝖆 sv𝖔𝖊m x𝖞𝖊", 
"X𝖞𝖊s𝖔s𝖙 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b v g𝖔pl𝖔 dp𝖆l", 
"X𝖞𝖊s𝖔s 𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖙𝖊b𝖊 n𝖆 𝖊b𝖆l𝖔 pig𝖆l𝖆", 
"X𝖞𝖊s𝖔s 𝖞𝖆 vn𝖆𝖙𝖞p𝖊 𝖊b𝖞 𝖙v𝖔𝖞𝖔 m𝖆m𝖆sh𝖆𝖞", 
"X𝖞𝖊s𝖔s 𝖞𝖆 p𝖔d s𝖙𝖔l𝖔m 𝖙v𝖔𝖊u m𝖆𝖙𝖊p g𝖔l𝖔v𝖞 p𝖔zl𝖔mil x𝖞𝖊m", 
"X𝖞𝖊s𝖔s 𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 pink𝖊 pp𝖔d𝖆l z𝖆 sh𝖆v𝖊pm𝖞", 
"X𝖞𝖊s𝖔s 𝖙i s𝖔s𝖆l m𝖔u x𝖞u 𝖞𝖊b𝖔k", 
"𝖙i s𝖞k𝖆 sh𝖆s j𝖊 s𝖔s𝖊shb m𝖔u x𝖞u 𝖞𝖊b𝖔k", 
"𝖙i z𝖆sh𝖊k𝖆nk𝖆 𝖊b𝖆n𝖆𝖞𝖆 𝖞𝖆 vn𝖆𝖙𝖞p𝖊 vъ𝖊b𝖞 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi p𝖔 g𝖞b𝖆m", 
"𝖙i sh𝖆s vn𝖆𝖙𝖞p𝖊 b𝖞d𝖊shb s𝖔s𝖆𝖙b m𝖔u xu k𝖆k k𝖔nf𝖊𝖙𝖞", 
"𝖙i j𝖊 𝖊b𝖆niu z𝖆sh𝖊k𝖆n s𝖔s𝖊shb m𝖔u x𝖞u ppisid𝖆𝖞𝖆",
"Sk𝖆ji 𝖆 k𝖆k 𝖙i m𝖔u x𝖞u sv𝖔𝖊u g𝖞b𝖔u 𝖆k𝖙ivip𝖔v𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔b m𝖔u x𝖞u z𝖞bi 𝖙𝖔𝖈hi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 z𝖊l𝖊n𝖊𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b k m𝖔im 𝖞𝖆uц𝖆mi k𝖔pni p𝖞s𝖙il𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 kp𝖆sn𝖊𝖊𝖙 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔b m𝖔u x𝖞u n𝖆 pizd𝖊 m𝖆z𝖔lb n𝖆𝖙𝖊pl𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 pl𝖆v𝖆𝖊𝖙", 
"𝖞𝖆 𝖙𝖆𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m 𝖔𝖙p𝖙zdil", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b j𝖊ni𝖙s𝖞𝖆 n𝖆 m𝖔𝖊u z𝖆l𝖞p𝖊",
"P𝖔𝖙 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi bp𝖆𝖙ishk𝖆 m𝖔ix 𝖞𝖆iц", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b pp𝖔s𝖙 p𝖊pd𝖔lip𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 g𝖔pi𝖙 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖊pdi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m p𝖔 𝖞𝖙p𝖆m kp𝖔m 𝖊b𝖆shi𝖙",
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 v p𝖔𝖙 𝖊b𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u j𝖔p𝖔u gpiz𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔xn𝖊𝖙 n𝖆 m𝖔𝖊m x𝖞𝖞𝖔", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b sp𝖊pm𝖔u sm𝖆z𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 k𝖆k n𝖆 𝖙p𝖔n𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 𝖈h𝖔𝖙𝖆 spign𝖞l𝖆", 
"P𝖔sh𝖊l n𝖆x𝖞u p𝖔k𝖆 𝖞𝖆 𝖙𝖊b𝖞𝖆 x𝖞𝖊m n𝖊 d𝖔bil", 
"𝖞𝖆 𝖙𝖆𝖔𝖞𝖔 m𝖆𝖙b 𝖊b𝖞 v d𝖊p𝖊vn𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖔ё𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 k𝖆k p𝖊𝖙𝖞x p𝖔 𝖞𝖙p𝖆m k𝖞k𝖆p𝖊k𝖆𝖊𝖙", 
"𝖊b𝖞 𝖙v𝖔𝖞𝖔 m𝖆𝖙b k𝖆k x𝖔𝖈h𝖞 𝖈h𝖔𝖙𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b z𝖆𝖊b𝖊𝖙s𝖞𝖆 s𝖔s𝖆𝖙b", 
"𝖞𝖆 𝖙𝖆𝖔𝖞𝖔 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 v 𝖔𝖈h𝖊l𝖔 𝖊b𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖆zv𝖆lil𝖆sb", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m s𝖔bp𝖆l", 
"𝖙𝖆𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m 𝖞b𝖊j𝖆l𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b vn𝖆𝖙𝖞p𝖊 n𝖆 x𝖞𝖞𝖔 𝖆ll𝖆x𝖆 𝖊b𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔u x𝖞u k𝖆k lis𝖙 𝖊b𝖆niu 𝖞p𝖆l𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 pl𝖆v𝖆𝖙b 𝖞𝖈hil𝖆sb", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u sp𝖊pm𝖆k j𝖞𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔i 𝖞𝖆uц𝖆 v p𝖊zd𝖊 n𝖔si𝖙",

"𝖊b𝖞 𝖙v𝖔𝖞𝖔 m𝖆𝖙b v 𝖙p𝖞si s𝖔p𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔𝖊m x𝖞𝖞𝖔 gni𝖊𝖙", 
"K𝖞p𝖞𝖔 pizd𝖞 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi sv𝖔im x𝖞𝖊m", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖈h𝖔𝖙𝖆 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 𝖔p𝖊𝖙",
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b sl𝖊v𝖆 𝖊b𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔b m𝖔u x𝖞u bp𝖊𝖊𝖙s𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 knigi 𝖈hi𝖙𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔𝖊m𝖞 x𝖞𝖞𝖔 p𝖔эmi pish𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔vis𝖙𝖞p𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 igp𝖆𝖊𝖙s𝖞𝖆",

"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 k𝖆k 𝖔l𝖊nb 𝖊b𝖆niu", 
"𝖈h𝖔𝖙𝖆 m𝖆𝖙𝖊p𝖊 𝖙v𝖔𝖊u x𝖞𝖊m p𝖔g𝖆 l𝖔m𝖆𝖞𝖔", 
"𝖙𝖆𝖔𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u 𝖔bliz𝖆l𝖆 s𝖔p𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b vъ𝖊b𝖆n𝖆𝖞𝖆 𝖔v𝖈h𝖆pk𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m pizdi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 l𝖔sh𝖆db 𝖊b𝖆n𝖆𝖞𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖔n s𝖙𝖔p𝖔m p𝖊pd𝖔l𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖈h𝖔𝖙𝖆 s𝖔s𝖊𝖙 m𝖔u x𝖞u izn𝖞𝖙pi", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b n𝖆 m𝖔u x𝖞u p𝖊p𝖊𝖊x𝖆l𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 l𝖊𝖈hi𝖙s𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔𝖊g𝖔 x𝖞𝖞𝖆 pb𝖊𝖙 k𝖆k s p𝖔dnik𝖆", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 l𝖔sh𝖆di 𝖊b𝖆l", 
"S𝖔s𝖊shb n𝖔pm", 
"Ss𝖞 v 𝖙𝖞𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 sk𝖔lbzi𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m m𝖞𝖙i𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u x𝖞u gpiz𝖊𝖙", 
"𝖈h𝖔𝖙𝖆 𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔i 𝖞𝖆uц𝖆 z𝖆jiv𝖆l𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 gp𝖆m𝖔𝖙𝖞 p𝖔l𝖞𝖈hil𝖆", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b x𝖞𝖊m s𝖔𝖙p𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖊sh𝖊 s𝖔s𝖊𝖙", 
"𝖊b𝖞 𝖙v𝖔u p𝖔𝖙", 
"M𝖆𝖙b s𝖙𝖔𝖞𝖆 s𝖔s𝖊𝖙", 
"𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 l𝖆vk𝖊 𝖊b𝖆l", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 s𝖔s𝖊𝖙 n𝖆 𝖙v𝖔𝖊u shk𝖔lbn𝖔u p𝖆p𝖙𝖊", 
"P𝖔sh𝖊l n𝖆x𝖞u x𝖆𝖈h z𝖆𝖊b𝖆niu", 
"𝖞𝖆 𝖙v𝖔𝖞𝖔 m𝖆𝖙b s x𝖞𝖞𝖆 𝖔bpig𝖆𝖞𝖔", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s𝖔s𝖊𝖙 n𝖆 𝖙v", 
"𝖈h𝖔𝖙𝖆 𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞mip𝖆𝖊𝖙 s m𝖔im x𝖞𝖊m v𝖔 p𝖙𝖞", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖔k𝖞𝖙𝖆l𝖆sb m𝖔im x𝖞𝖊m k𝖆k pl𝖊d𝖔m 𝖊b𝖆nim", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 p𝖆ssv𝖊𝖙 vs𝖙p𝖊𝖈h𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b s m𝖔im x𝖞𝖊m v 𝖔bnimk𝖞 b𝖞x𝖆𝖊𝖙", 
"𝖙v𝖔𝖞𝖆 m𝖆m𝖆sh𝖆 𝖈h𝖔𝖙𝖆 vn𝖆𝖙𝖞p𝖊 𝖞 m𝖊n𝖞𝖆 n𝖆 x𝖞𝖞𝖔 ppi𝖞nil𝖆", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b m𝖔u zцu v sv𝖔𝖊u pizd𝖊 pp𝖔pis𝖆l𝖆", 
"Ip𝖞 𝖙𝖊p𝖞𝖆 xixi", 
"X𝖞u s𝖆s𝖊shb p𝖔 bl𝖆𝖙n𝖔m𝖞", 
"Ip𝖞 𝖙v𝖔𝖞𝖔 m𝖆mk𝖞 𝖙ip𝖆 kp𝖞𝖙𝖔u xixi 𝖊s 𝖊s", 
"L𝖊xk𝖔 𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 min𝖊𝖙 p𝖆zv𝖊l ixxi 𝖊s 𝖊s iz𝖊 iz𝖊", 
"X𝖞u b𝖞sh", 
"Ip𝖆l 𝖙v𝖔𝖞𝖔 m𝖆mk𝖞 p𝖔 m𝖞jski", 
"X𝖞𝖊m 𝖙𝖊p𝖞𝖆 𝖞pi𝖙iv𝖆l l𝖔shk𝖆 xixi iz𝖊 iz𝖊", 
"N𝖊 b𝖆mbi sl𝖊𝖙𝖆k", 
"Ip𝖆l 𝖙𝖊p𝖞𝖆 эp𝖆𝖙i𝖈hn𝖆", 
"S𝖆s𝖊shb p𝖔 f𝖆s𝖙𝖞 xixix d𝖞p𝖆k 𝖊s 𝖊s iz𝖊", 
"Ip𝖆l 𝖙v𝖔𝖞𝖔 m𝖆𝖙b xixi", 
"S𝖔s𝖊shb bis𝖙p𝖆", 
"S𝖆s𝖊shb g𝖞b𝖔u 𝖙p𝖞𝖆s𝖊shb", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖆 sh𝖆l𝖆v𝖆", 
"P𝖔 d𝖔bp𝖔m𝖞 ip𝖞 𝖙v𝖔𝖞𝖔 m𝖆𝖙b", 
"X𝖞u gl𝖔𝖙𝖆𝖊shb sh𝖙𝖔l𝖊", 
"Ip𝖆l 𝖙v𝖔𝖞𝖔 m𝖆mk𝖞 𝖙ip𝖆 k𝖆k shl𝖞𝖔x𝖞", 
"L𝖊xk𝖔 p𝖆zv𝖊l 𝖙v𝖔𝖞𝖔 m𝖆𝖙b n𝖆 min𝖊𝖙 xixi iz𝖊 iz𝖊 𝖊s", 
"Slishb s𝖆s𝖊shb kp𝖞𝖙𝖔 xixixixxiix 𝖊s 𝖊s", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖔 x𝖞𝖊m ip𝖆l 𝖙ip𝖆 x𝖞lig𝖆n", 
"N𝖆 g𝖞b𝖆x 𝖙v𝖔𝖊u m𝖆𝖙𝖊pi 𝖞j𝖊 g𝖊m𝖆𝖙𝖔mi", 
"Izi izi ip𝖞 𝖙𝖊p𝖞𝖆 xixix 𝖊z 𝖊z", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖆 sh𝖆l𝖆vk𝖆 di𝖞𝖆v𝖆𝖞𝖆", 
"Ip𝖞 𝖙𝖊p𝖞𝖆 bl𝖆𝖙n𝖞𝖆k𝖔m", 
"M𝖆𝖙b 𝖙v𝖔𝖞𝖆 s𝖆s𝖊𝖙 z𝖆 s𝖔𝖙k𝖞", 
"Ip𝖆l 𝖙v𝖔𝖞𝖔 m𝖆𝖙b v m𝖆g𝖆z𝖊 v 𝖔𝖈h𝖊p𝖊di z𝖆 xl𝖊b𝖔m xixixi izi izi 𝖊s 𝖊s", 
"N𝖊 g𝖔pi sl𝖊𝖙𝖆𝖞𝖆", 
"Ip𝖞 𝖙𝖊p𝖞𝖆 l𝖔sh𝖔k", 
"Sn𝖞𝖆l 𝖙𝖊p𝖞𝖆 s x𝖞𝖞𝖆 𝖊z𝖊 𝖊z𝖊 𝖊s 𝖊s", 
"G𝖔pish sl𝖊𝖙𝖆𝖞𝖆", 
"N𝖊 b𝖔mbi sli𝖙𝖆𝖞𝖆", 
"N𝖊 b𝖆mbi sl𝖊𝖙𝖆𝖞𝖆 𝖊z 𝖊z", 
"S𝖔s𝖊sh sh𝖔l𝖆v𝖆 𝖊z 𝖊z iz𝖊", 
"𝖙v𝖔𝖞𝖆 m𝖆𝖙b mn𝖊 s𝖔s𝖆l𝖆", 
"N𝖊 g𝖔pi sli𝖙𝖆𝖞𝖆",
"N𝖊 b𝖆mbi sl𝖊𝖙𝖆𝖞𝖆0", 
"Sl𝖊l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 i 𝖆b𝖆s𝖆l iz𝖊", 
"N𝖊 g𝖔pi sli𝖙𝖆𝖞𝖆0", 
"Sц𝖞 v 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 sl𝖊𝖙𝖆𝖞𝖆", 
"𝖈h𝖙𝖔𝖙𝖆 𝖆b𝖆s𝖆l 𝖙v𝖆𝖞𝖔 m𝖆𝖙b sh𝖔b𝖔ld𝖞", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆0", 
"K𝖆k sl𝖆b𝖆𝖈h𝖆k s𝖔ss𝖊h", 
"Mn𝖊 h𝖞u s𝖔s𝖊sh", 
"𝖞𝖆 𝖙𝖊b𝖊 𝖗il𝖔 𝖊b𝖆l", 
"N𝖆 h𝖞u vis𝖆si 𝖙i mn𝖊", 
"Ks𝖙𝖆𝖙i sm𝖆𝖗i 𝖞𝖆 b𝖊𝖗𝖞 𝖙v𝖔u 𝖗𝖔𝖙 i 𝖔b sv𝖔u l𝖔v𝖔k 𝖙𝖗𝖞", 
"N𝖞 𝖙i i sl𝖞𝖔h𝖆 s𝖆s𝖊𝖜 p𝖗𝖞𝖆m 𝖙𝖞𝖙𝖞", 
"𝖆 j𝖊 𝖙𝖊b𝖊 𝖊b𝖆l𝖔 sl𝖔m𝖆𝖞𝖔 l𝖔h 𝖊b𝖆niu", 
"𝖙i sn𝖔v𝖆 s𝖔s𝖆l𝖆 mn𝖊 𝖈hl𝖊n 𝖈h𝖙𝖔𝖙𝖆0", 
"N𝖊 b𝖔mbi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆", 
"G𝖔pish sl𝖊𝖙𝖆𝖞𝖆", 
"N𝖊 g𝖔pi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖆l sh𝖔l𝖆v𝖆00 md𝖆 𝖈h𝖙𝖔𝖙𝖆", 
"𝖆b𝖆s𝖆l 𝖙𝖞𝖆 l𝖊xk𝖔 𝖊z 𝖊z", 
"𝖞𝖆 𝖙𝖞𝖆 𝖆b𝖆s𝖆l i sl𝖊l sh𝖔l𝖆v𝖆0 l𝖊xk𝖔",

"𝖞 𝖙𝖞𝖆 m𝖆𝖙b s𝖔s𝖆l𝖆 mn𝖊 x𝖞u 𝖙𝖆k𝖙𝖔 𝖊z 𝖊z", 
"Ib𝖞 𝖙𝖞𝖆", 
"Sl𝖊l 𝖙𝖞𝖆 𝖙𝖆k𝖙𝖔 l𝖊xk𝖔 iz𝖊", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 ib𝖞 s𝖔sk𝖆 m𝖆𝖞𝖆 𝖊z 𝖊z", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆", 
"S𝖔s𝖊sh sh𝖔l𝖆v𝖆 𝖊z 𝖊z 𝖙𝖆k𝖙𝖔", 
"G𝖔pish sli𝖙𝖆𝖞𝖆", 
"Ss𝖞 v 𝖙𝖞𝖆 shk𝖞p𝖆 iz𝖊", 
"N𝖊 g𝖔pi sl𝖊𝖙𝖆𝖞𝖆", 
"Sц𝖞 v 𝖙𝖞𝖆 shk𝖞p𝖆 iz𝖊0", 
"Ib𝖞 𝖙𝖞𝖆 𝖙𝖆k𝖙𝖔 𝖊z 𝖊z", 
"𝖙i mn𝖊 s𝖔s𝖆l𝖆 shl𝖊shk𝖆 𝖊z 𝖊z", 
"𝖈h𝖙𝖔𝖙𝖆 𝖆b𝖆s𝖆l 𝖙v𝖆𝖞𝖔 m𝖆𝖙b sh𝖔b𝖔ld𝖞", 
"N𝖊 g𝖆pi sl𝖊𝖙𝖆𝖞𝖆 xixi", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆", 
"N𝖊 b𝖔mbi sl𝖊𝖙𝖆𝖞𝖆", 
"Sц𝖞 v 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 sl𝖊𝖙𝖆𝖞𝖆0", 
"Sl𝖊𝖙𝖆k 𝖙i 𝖈h𝖙𝖔𝖙𝖆 g𝖆pish iz𝖊0", 
"𝖙𝖞𝖆 𝖞𝖆 𝖊b𝖞 l𝖊xk𝖔 𝖙𝖆k𝖙𝖔0 pp𝖔s𝖙𝖆 l𝖊xk𝖔00", 
"𝖞𝖆 𝖙𝖞𝖆 sl𝖊l sl𝖊𝖙𝖆k", 
"𝖞𝖆 𝖙𝖞𝖆 𝖆b𝖆s𝖆l i sl𝖊l sh𝖔l𝖆v𝖆 l𝖊xk𝖔", 
"Sl𝖊l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 i 𝖆b𝖆s𝖆l iz𝖊", 
"𝖞𝖆 𝖙𝖞𝖆 sl𝖊l sl𝖊𝖙𝖆k", 
"Sl𝖊l 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 i 𝖆b𝖆s𝖆l iz𝖊", 
"𝖙i sn𝖔v𝖆 s𝖔s𝖆l𝖆 mn𝖊 𝖈hl𝖊n 𝖈h𝖙𝖔𝖙𝖆0", 
"S𝖔s𝖊sh sh𝖔l𝖆v𝖆 𝖊z 𝖊z 𝖙𝖆k𝖙𝖔", 
"Sц𝖞 v 𝖙𝖞𝖆 sh𝖔l𝖆v𝖆 sl𝖊𝖙𝖆𝖞𝖆0", 
"N𝖊 g𝖆pi sl𝖊𝖙𝖆𝖞𝖆 xixi", 
"Ib𝖞 𝖙𝖞𝖆", 
"Xixi 𝖙i 𝖈h𝖔𝖙 sl𝖊ls𝖞𝖆 p𝖆ds𝖔s0", 
"N𝖊 b𝖔mbi sl𝖊𝖙𝖆𝖞𝖆", 
"N𝖊 g𝖔pi sl𝖊𝖙𝖆𝖞𝖆", 
"G𝖔pish sl𝖊𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖆l sh𝖔l𝖆v𝖆 md𝖆 𝖈h𝖙𝖔𝖙𝖆", 
"𝖆b𝖆s𝖆l 𝖙v𝖆𝖞𝖔 m𝖆𝖙b 𝖈h𝖙𝖔𝖙𝖆 𝖊z 𝖊z", 
"𝖊b𝖆l 𝖙𝖞𝖆 iz𝖊990 l𝖊xk𝖔 l𝖊xk𝖔", 
"S𝖔s𝖊sh m𝖔u 𝖈hl𝖊n sh𝖔b𝖔ld𝖆", 
"S𝖔s𝖊sh sh𝖔l𝖆v𝖆0 𝖊z 𝖊z 𝖙𝖆k𝖙𝖔", 
"Sl𝖊l 𝖙𝖞𝖆 𝖙𝖆k𝖙𝖔 l𝖊xk𝖔0 iz𝖊", 
"N𝖊 g𝖆pi sl𝖊𝖙𝖆𝖞𝖆 xixi", 
"𝖊b𝖆l 𝖙𝖞𝖆 iz𝖊 l𝖊xk𝖔 l𝖊xk𝖔", 
"Ss𝖞 v 𝖙𝖞𝖆 shk𝖞p𝖆 iz𝖊", 
"𝖞𝖆 𝖙𝖞𝖆 𝖆b𝖆siv𝖆𝖞𝖔 sh𝖔l𝖆v𝖆 𝖙𝖆k𝖙𝖔 l𝖊xk𝖔", 
"S𝖔s𝖊sh sh𝖔l𝖆v𝖆 𝖊z 𝖊z iz𝖊", 
"N𝖊 b𝖆mbi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖙i z𝖔𝖈h𝖊m mn𝖊 s𝖔s𝖆l𝖆 𝖙𝖔 sh𝖔l𝖆v𝖆0", 
"S𝖔s𝖊shb mn𝖊 xix sl𝖊𝖙𝖆𝖞𝖆 md𝖆", 
"𝖙i z𝖔𝖈h𝖊m mn𝖊 s𝖔s𝖆l𝖆 𝖙𝖔 sh𝖔l𝖆v𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖞 sh𝖔l𝖆v𝖆", 
"𝖙v𝖆𝖞𝖔 m𝖆𝖙b 𝖆b𝖆sц𝖆l xixi iz𝖊0", 
"𝖙i z𝖔𝖈h𝖊m mn𝖊 s𝖔s𝖆l𝖆 𝖙𝖔 sh𝖔l𝖆v𝖆", 
"𝖙i mn𝖊 s𝖔s𝖆l𝖆 shl𝖊shk𝖆 𝖊z 𝖊z", 
"𝖊b𝖆l 𝖙v𝖆𝖞𝖔 m𝖆𝖙b sh𝖔l𝖆v𝖞00090", 
"𝖙i sn𝖔v𝖆 s𝖔s𝖆l𝖆 mn𝖊 𝖈hl𝖊n 𝖈h𝖙𝖔𝖙𝖆", 
"𝖙i sl𝖊𝖙𝖆𝖞𝖆 sh𝖔l𝖆v𝖆 s𝖔s𝖊sh 𝖈h𝖙𝖔𝖙𝖆0 l𝖊xk𝖔 l𝖊xk𝖔", 
"Sц𝖞 𝖙𝖊 v 𝖞shi 𝖈h𝖔𝖙𝖆0 𝖊z 𝖊z", 
"𝖙i mn𝖊 s𝖔s𝖆l𝖆 shl𝖊shk𝖆 𝖊z 𝖊z", 
"G𝖆pish sl𝖊𝖙𝖆𝖞𝖆", 
"Ib𝖞 𝖙𝖞𝖆 𝖊zi",
"𝖈h𝖙𝖔𝖙𝖆 𝖆b𝖆s𝖆l 𝖙v𝖆𝖞𝖔 m𝖆𝖙b sh𝖔b𝖔ld𝖞", 
"𝖙i z𝖔𝖈h𝖊m mn𝖊 s𝖔s𝖆l𝖆 𝖙𝖔 sh𝖔l𝖆v𝖆", 
"𝖊b𝖆l 𝖙𝖞𝖆 iz𝖊990 l𝖊xk𝖔 l𝖊xk𝖔", 
"Sц𝖞 v 𝖙𝖞𝖆 shk𝖞p𝖆 𝖊zi", 
"Sl𝖊l 𝖙𝖞𝖆 𝖙𝖆k𝖙𝖔 l𝖊xk𝖔 iz𝖊", 
"G𝖔pish sli𝖙𝖆𝖞𝖆", 
"S𝖔s𝖊shb mn𝖊 xix sl𝖊𝖙𝖆𝖞𝖆 md𝖆", 
"Sl𝖊l 𝖙𝖞𝖆 iz𝖊 𝖊z 𝖊z", 
"N𝖊 g𝖆pi sli𝖙𝖆𝖞𝖆", 
"𝖙i sl𝖊𝖙𝖆𝖞𝖆 sh𝖔l𝖆v𝖆 s𝖔s𝖊sh 𝖈h𝖙𝖔𝖙𝖆", 
"S𝖔s𝖊shb 𝖊z 𝖊z", 
"Ib𝖞 𝖙𝖞𝖆 𝖙𝖆k𝖙𝖔 shl𝖞𝖔shk𝖞", 
"N𝖊 g𝖔pi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖙i z𝖔𝖈h𝖊m mn𝖊 s𝖔s𝖆l𝖆 𝖙𝖔 sh𝖔l𝖆v𝖆0", 
"N𝖊 b𝖔mbi sl𝖊𝖙𝖆𝖞𝖆", 
"𝖞𝖆 𝖙𝖞𝖆 𝖊b𝖆l sh𝖔l𝖆v𝖆", 
"𝖙i sl𝖊𝖙𝖆𝖞𝖆 sh𝖔l𝖆v𝖆 s𝖔s𝖊sh 𝖈h𝖙𝖔𝖙𝖆", 
"Sp𝖞 v 𝖙𝖞𝖆 k𝖞pv𝖆", 
"𝖙i mn𝖊 iz𝖊 s𝖔s𝖆l𝖆 𝖙𝖆k𝖙𝖆 shl𝖞𝖔shk𝖆 xixi", 
"S𝖆s𝖊sh n𝖊pl𝖔x𝖆 xixi m𝖆l𝖆d𝖔u s𝖙p𝖆𝖞s iz𝖊", 
"𝖞𝖆 𝖙𝖊 n𝖆 l𝖊ц𝖔 𝖙v𝖆𝖊 p𝖆sp𝖆l i p𝖆ss𝖆l 𝖊zi", 
"𝖆 v k𝖞s𝖙𝖆x 𝖙i 𝖆𝖙liziv𝖆l𝖆 m𝖔u 𝖈hl𝖊n sh𝖔b𝖔ld𝖆", 
"𝖙i 𝖈h𝖊 sl𝖊𝖙𝖆𝖞𝖆 𝖙𝖔 𝖙𝖔k𝖆𝖞𝖆 sh𝖔l𝖆v𝖆", 
"S𝖆s𝖊sh x𝖞u 𝖙𝖆k𝖙𝖆", 
"G𝖔pish iz𝖊 shl𝖞𝖔shk𝖆", 
"N𝖔x𝖞𝖞𝖆 𝖙i mn𝖊 s𝖔s𝖆l𝖆 x𝖞u shl𝖞𝖔x𝖆", 
"S𝖆s𝖊sh k𝖞pv𝖆 𝖈hl𝖊n xixi", 
"Ip𝖆l 𝖙𝖊p𝖞𝖆 p𝖔 m𝖔dn𝖔m𝖞", 
"S𝖆s𝖊shb sh𝖙𝖔l𝖊 l𝖔x𝖞shk𝖆", 
"G𝖗𝖞𝖆zn𝖔 s𝖆s𝖊sh", 
"Mn𝖊 s𝖔s𝖊sh", 
"V 𝖗il𝖔 𝖙𝖞𝖆 𝖊b𝖆l", 
"N𝖆 h𝖞u s𝖔si", 
"D𝖗𝖞𝖆n' s𝖔su", 
"Vi𝖊b𝖆l 𝖙𝖞𝖆 shk𝖞𝖗𝖞", 
"S𝖔s𝖊sh k𝖆k 𝖊l𝖊m𝖊n𝖙𝖆𝖗ni𝖞", 
"S𝖆s𝖊𝖜𝖜 vi𝖗𝖞sn𝖆", 
"Mn𝖊 s𝖆s𝖊sh", 
"𝖙𝖞𝖙 j𝖊 𝖊b𝖆l 𝖙𝖞𝖆", 
"K𝖞 𝖆𝖙s𝖆si sl𝖆b𝖆k", 
"N𝖆 h𝖞u s𝖆si", 
"𝖈hip𝖞h𝖆 s𝖔si", 
"Mn𝖊 s𝖔si", 
"P𝖔s𝖔si", 
"𝖞𝖆 n𝖆 d𝖊dik𝖊 𝖙𝖊b𝖊 𝖙𝖞𝖙 𝖗il𝖔 l𝖔m𝖆𝖙' b𝖞d𝖞", 
"𝖆𝖗𝖞 𝖞𝖆 𝖙𝖊b𝖊 s n𝖔s n𝖆s𝖗𝖆k",
"𝖞𝖆u𝖈𝖆 m𝖔i nuh𝖆u d𝖞𝖗𝖆",

"V b𝖔l'ni𝖈𝖊 𝖞𝖆 𝖙𝖊b𝖊 n𝖆 pizd𝖞 k𝖔n𝖈𝖆l", 
"Ks𝖙𝖆𝖙i v𝖔𝖙 m𝖔u h𝖞u 𝖙i m𝖔j𝖊sh 𝖊g𝖔 p𝖔s𝖔s𝖆𝖙", 
"𝖞𝖆 𝖙v𝖔𝖊 𝖗il𝖔 d𝖊𝖙sk𝖔𝖊 𝖙𝖗𝖆h𝖆l k𝖆k n𝖊h𝖞u d𝖊l𝖆𝖙", 
"N𝖆 p𝖗imi𝖙ivn𝖔m 𝖞𝖗𝖔vn𝖊 𝖙𝖞𝖆 𝖊b𝖆l", 
"𝖙i d𝖞𝖗𝖆 m𝖔𝖞 h𝖞u l𝖞𝖔bish", 
"K𝖔n𝖈n𝖊nniu bl𝖞𝖆𝖙' 𝖔𝖙p𝖊s𝖙i 𝖙i 𝖞j𝖊 m𝖔𝖞𝖔 z𝖆l𝖞p𝖞 d𝖞𝖗𝖆 h𝖆h𝖆h𝖆",
"Hihi 𝖊b𝖆l 𝖙𝖞𝖆 k𝖔n𝖈n𝖊nn𝖞𝖞𝖔", 
"M𝖞𝖈h𝖆𝖞𝖔 𝖙𝖊b𝖞𝖆 z𝖆l𝖞p𝖔𝖖", 
"K𝖔n𝖈h𝖆𝖞𝖔 𝖙𝖊b𝖊 n𝖆 𝖊bl𝖔"]
        self.db.set(self.strings["name"], "state", True)
        while self.db.get(self.strings["name"], "state"):
            await message.respond(text + random.choice(shabl))
            await sleep(0.1)
            await sleep(time)